In [1]:
# ============================================================
# Fine-tuning済み Coarse-only 最終モデル：101ペア完全評価
#
# 出力：
# - pairwise_metrics_finetuned_coarse_only.csv
# - summary_metrics_finetuned_coarse_only.csv
#
# 評価：
# Dice, Jaccard, NCC, RMSE[HU], SSIM, MS-SSIM, FSIM
# 全画素Folding, valid-Body Folding, interior valid-Body Folding
# z=60–68 interior Folding, 肺野Dice, 肺野Folding
# ============================================================

import os
os.environ["VXM_BACKEND"] = "pytorch"

from pathlib import Path
import re
import gc
import math

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

import voxelmorph as vxm

from scipy.ndimage import (
    binary_fill_holes,
    binary_opening,
    binary_erosion,
    label,
)

from skimage.metrics import structural_similarity
from tqdm.auto import tqdm

backend:pytorch
Pytorch

In [2]:
# ------------------------------------------------------------
# 1. パス・設定
# ------------------------------------------------------------

TEST_DATA_ROOT = Path(
    r"D:\Saito\Data\TestData"
)

FINETUNED_MODEL_PATH = Path(
    r"D:\Saito\fullres_trilinear_ic_beta1e3_80k"
    r"\coarse_only_lll_ic_finetune_30k"
    r"\model_coarse_only_lll_ic_finetuned_30k_final.pth"
)

EVAL_DIR = (
    FINETUNED_MODEL_PATH.parent
    / "testdata_evaluation_finetuned_30k"
)

EVAL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

MODEL_NAME = "30k_coarse_only_finetuned"

FULL_SIZE = (128, 256, 256)
LOW_SIZE = (64, 128, 128)

HU_MIN = -1024.0
HU_MAX = 3071.0
BODY_THRESHOLD = 0.10

# 体表・画像端から除外する幅
INTERIOR_MARGIN_VOXELS = 5

# slice 64周辺の確認範囲
Z_CENTER = 64
Z_RADIUS = 4
Z_START = Z_CENTER - Z_RADIUS
Z_END = Z_CENTER + Z_RADIUS

DEVICE = torch.device(
    "cuda:0"
    if torch.cuda.is_available()
    else "cpu"
)

if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

try:
    torch.set_float32_matmul_precision("high")
except AttributeError:
    pass

if not TEST_DATA_ROOT.is_dir():
    raise FileNotFoundError(
        f"TestDataが見つかりません:\n{TEST_DATA_ROOT}"
    )

if not FINETUNED_MODEL_PATH.is_file():
    raise FileNotFoundError(
        f"Fine-tuning済み重みが見つかりません:\n"
        f"{FINETUNED_MODEL_PATH}"
    )

print("Device      :", DEVICE)
print("TestData    :", TEST_DATA_ROOT)
print("Model       :", FINETUNED_MODEL_PATH)
print("Output dir  :", EVAL_DIR)

Device      : cuda:0
TestData    : D:\Saito\Data\TestData
Model       : D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\model_coarse_only_lll_ic_finetuned_30k_final.pth
Output dir  : D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_finetuned_30k

In [3]:
# ------------------------------------------------------------
# 2. Haar DWT・モデル定義
# ------------------------------------------------------------

class Haar3DAnalysis(nn.Module):

    def __init__(self):
        super().__init__()

        h_low = torch.tensor(
            [1.0, 1.0],
            dtype=torch.float32,
        ) / math.sqrt(2.0)

        h_high = torch.tensor(
            [1.0, -1.0],
            dtype=torch.float32,
        ) / math.sqrt(2.0)

        filters = []

        for z_filter in [h_low, h_high]:
            for y_filter in [h_low, h_high]:
                for x_filter in [h_low, h_high]:
                    kernel = (
                        z_filter[:, None, None]
                        * y_filter[None, :, None]
                        * x_filter[None, None, :]
                    )
                    filters.append(kernel)

        self.register_buffer(
            "weight",
            torch.stack(
                filters,
                dim=0,
            ).unsqueeze(1),
        )

    def forward(self, image):
        return F.conv3d(
            image,
            self.weight,
            stride=2,
            padding=0,
        )


def low_dvf_to_full_trilinear(flow_low):
    return F.interpolate(
        flow_low.float(),
        size=FULL_SIZE,
        mode="trilinear",
        align_corners=False,
    ) * 2.0


nb_features = [
    [32, 64, 64, 64, 64],
    [64, 64, 64, 64, 64, 32, 16, 16],
]


def create_single_voxelmorph():
    return vxm.networks.VxmDense_128_256_256(
        FULL_SIZE,
        nb_features,
        nb_features,
        int_steps=0,
    )

In [4]:

# ------------------------------------------------------------
# 3. モデル読込
# ------------------------------------------------------------

try:
    checkpoint = torch.load(
        FINETUNED_MODEL_PATH,
        map_location="cpu",
        weights_only=False,
    )
except TypeError:
    checkpoint = torch.load(
        FINETUNED_MODEL_PATH,
        map_location="cpu",
    )

state_dict = checkpoint.get(
    "model_state_dict",
    checkpoint,
)

state_dict = {
    key.replace("_orig_mod.", "", 1): value
    for key, value in state_dict.items()
}

analysis = Haar3DAnalysis().to(DEVICE)
analysis.eval()

model = create_single_voxelmorph().to(DEVICE)

model.load_state_dict(
    state_dict,
    strict=True,
)

model.eval()

transformer_full = vxm.layers.SpatialTransformer(
    FULL_SIZE
).to(DEVICE)

transformer_full.eval()

print("\nFine-tuned Coarse-only model loading completed.")

[64, 128, 128]

Fine-tuned Coarse-only model loading completed.

c:\Users\user\anaconda3\envs\nn\lib\site-packages\torch\functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

In [5]:
# ------------------------------------------------------------
# 4. データ読込
# ------------------------------------------------------------

def natural_sort_key(path):
    numbers = re.findall(
        r"\d+",
        path.name,
    )

    return [
        int(number)
        for number in numbers
    ] if numbers else [path.name]


def load_volume(path):
    path = Path(path)

    if path.suffix.lower() == ".npy":
        volume = np.load(path)

    elif path.suffix.lower() == ".npz":
        archive = np.load(path)

        preferred_keys = [
            "image",
            "volume",
            "ct",
            "data",
            "arr_0",
        ]

        selected_key = next(
            (
                key
                for key in preferred_keys
                if key in archive.files
            ),
            archive.files[0],
        )

        volume = archive[selected_key]

    else:
        raise ValueError(
            f"未対応形式です: {path}"
        )

    volume = np.asarray(volume).squeeze()

    if tuple(volume.shape) != FULL_SIZE:
        raise ValueError(
            f"shape={volume.shape}, "
            f"expected={FULL_SIZE}\n{path}"
        )

    return volume.astype(np.float32)


def find_fixed_moving_paths(pair_dir):
    files = sorted(
        list(pair_dir.rglob("*.npz"))
        + list(pair_dir.rglob("*.npy")),
        key=natural_sort_key,
    )

    fixed_candidates = [
        path
        for path in files
        if (
            "fixed" in path.name.lower()
            or "target" in path.name.lower()
        )
    ]

    moving_candidates = [
        path
        for path in files
        if (
            "moving" in path.name.lower()
            or "move" in path.name.lower()
            or "source" in path.name.lower()
        )
    ]

    if fixed_candidates and moving_candidates:
        return fixed_candidates[0], moving_candidates[0]

    if len(files) < 2:
        raise FileNotFoundError(
            f"Fixed / Moving画像を見つけられません:\n"
            f"{pair_dir}"
        )

    return files[0], files[1]

In [6]:
# ------------------------------------------------------------
# 5. 評価関数
# ------------------------------------------------------------

def compute_ncc(first, second):
    first = first.astype(np.float64)
    second = second.astype(np.float64)

    first = first - first.mean()
    second = second - second.mean()

    return float(
        np.sum(first * second)
        / (
            np.sqrt(
                np.sum(first ** 2)
                * np.sum(second ** 2)
            )
            + 1e-12
        )
    )


def make_body_mask(image):
    image_01 = np.clip(image, 0.0, 1.0)

    return binary_fill_holes(
        image_01 > BODY_THRESHOLD
    ).astype(bool)


def keep_largest_components(
    mask,
    n_components=2,
):
    labeled, count = label(mask)

    if count == 0:
        return np.zeros_like(
            mask,
            dtype=bool,
        )

    sizes = np.bincount(labeled.ravel())
    sizes[0] = 0

    selected = np.argsort(sizes)[
        -n_components:
    ]

    return np.isin(
        labeled,
        selected,
    )


def make_lung_mask(image):
    image_01 = np.clip(image, 0.0, 1.0)

    image_hu = (
        image_01
        * (HU_MAX - HU_MIN)
        + HU_MIN
    )

    body = make_body_mask(image_01)

    lung_candidate = (
        (image_hu >= -1000.0)
        & (image_hu <= -300.0)
        & body
    )

    lung_candidate = binary_opening(
        lung_candidate,
        iterations=1,
    )

    return keep_largest_components(
        lung_candidate,
        n_components=2,
    ).astype(bool)


def dice_jaccard(mask_a, mask_b):
    intersection = np.logical_and(
        mask_a,
        mask_b,
    ).sum()

    union = np.logical_or(
        mask_a,
        mask_b,
    ).sum()

    dice = (
        2.0 * intersection
        / (mask_a.sum() + mask_b.sum() + 1e-12)
    )

    jaccard = (
        intersection
        / (union + 1e-12)
    )

    return float(dice), float(jaccard)


def compute_mean_ssim(fixed, moved):
    values = []

    for z in range(fixed.shape[0]):
        values.append(
            structural_similarity(
                np.clip(fixed[z], 0.0, 1.0),
                np.clip(moved[z], 0.0, 1.0),
                data_range=1.0,
            )
        )

    return float(np.mean(values))


def compute_ms_ssim_fsim(fixed, moved):
    try:
        import piq
    except ImportError:
        return np.nan, np.nan

    fixed_tensor = torch.from_numpy(
        np.clip(fixed, 0.0, 1.0).astype(np.float32)
    ).unsqueeze(1).to(DEVICE)

    moved_tensor = torch.from_numpy(
        np.clip(moved, 0.0, 1.0).astype(np.float32)
    ).unsqueeze(1).to(DEVICE)

    ms_ssim_value = np.nan
    fsim_value = np.nan

    try:
        ms_ssim_value = piq.multi_scale_ssim(
            moved_tensor,
            fixed_tensor,
            data_range=1.0,
            reduction="mean",
        ).item()
    except Exception as error:
        print("MS-SSIM skipped:", repr(error))

    try:
        middle = fixed.shape[0] // 2

        fsim_value = piq.fsim(
            moved_tensor[middle:middle + 1],
            fixed_tensor[middle:middle + 1],
            data_range=1.0,
            chromatic=False,
            reduction="mean",
        ).item()

    except TypeError:
        fsim_value = piq.fsim(
            moved_tensor[middle:middle + 1],
            fixed_tensor[middle:middle + 1],
            data_range=1.0,
            reduction="mean",
        ).item()

    except Exception as error:
        print("FSIM skipped:", repr(error))

    del fixed_tensor
    del moved_tensor

    return ms_ssim_value, fsim_value


def jacobian_determinant(flow_np):
    uz, uy, ux = flow_np

    duz_dz, duz_dy, duz_dx = np.gradient(
        uz,
        edge_order=1,
    )

    duy_dz, duy_dy, duy_dx = np.gradient(
        uy,
        edge_order=1,
    )

    dux_dz, dux_dy, dux_dx = np.gradient(
        ux,
        edge_order=1,
    )

    j11 = 1.0 + duz_dz
    j12 = duz_dy
    j13 = duz_dx

    j21 = duy_dz
    j22 = 1.0 + duy_dy
    j23 = duy_dx

    j31 = dux_dz
    j32 = dux_dy
    j33 = 1.0 + dux_dx

    return (
        j11 * (j22 * j33 - j23 * j32)
        - j12 * (j21 * j33 - j23 * j31)
        + j13 * (j21 * j32 - j22 * j31)
    ).astype(np.float32)


def valid_reference_mask(
    flow_full,
    margin=0,
):
    _, _, depth, height, width = flow_full.shape

    z = torch.arange(
        depth,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, depth, 1, 1)

    y = torch.arange(
        height,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, 1, height, 1)

    x = torch.arange(
        width,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, 1, 1, width)

    reference_z = z + flow_full[:, 0:1].float()
    reference_y = y + flow_full[:, 1:2].float()
    reference_x = x + flow_full[:, 2:3].float()

    margin = float(margin)

    valid = (
        (reference_z >= margin)
        & (reference_z <= float(depth - 1) - margin)
        & (reference_y >= margin)
        & (reference_y <= float(height - 1) - margin)
        & (reference_x >= margin)
        & (reference_x <= float(width - 1) - margin)
    )

    return valid[0, 0].cpu().numpy().astype(bool)


def warp_mask_nearest(mask_np, flow_full):
    mask_tensor = torch.from_numpy(
        mask_np.astype(np.float32)
    ).unsqueeze(0).unsqueeze(0).to(DEVICE)

    _, _, depth, height, width = flow_full.shape

    z = torch.arange(
        depth,
        device=DEVICE,
        dtype=torch.float32,
    )

    y = torch.arange(
        height,
        device=DEVICE,
        dtype=torch.float32,
    )

    x = torch.arange(
        width,
        device=DEVICE,
        dtype=torch.float32,
    )

    zz, yy, xx = torch.meshgrid(
        z, y, x,
        indexing="ij",
    )

    grid = torch.stack(
        [zz, yy, xx],
        dim=0,
    ).unsqueeze(0)

    grid = grid + flow_full.float()

    grid[:, 0] = (
        2.0 * grid[:, 0]
        / max(depth - 1, 1)
        - 1.0
    )

    grid[:, 1] = (
        2.0 * grid[:, 1]
        / max(height - 1, 1)
        - 1.0
    )

    grid[:, 2] = (
        2.0 * grid[:, 2]
        / max(width - 1, 1)
        - 1.0
    )

    grid = grid.permute(
        0, 2, 3, 4, 1
    )[..., [2, 1, 0]]

    warped = F.grid_sample(
        mask_tensor,
        grid,
        mode="nearest",
        padding_mode="zeros",
        align_corners=True,
    )

    return (
        warped[0, 0].cpu().numpy() > 0.5
    )


def folding_percent(jacobian, mask):
    if mask.sum() == 0:
        return np.nan

    return float(
        np.mean(jacobian[mask] <= 0.0)
        * 100.0
    )

In [7]:

# ------------------------------------------------------------
# 6. 1ペア評価
# ------------------------------------------------------------

@torch.no_grad()
def evaluate_pair(pair_dir):
    fixed_path, moving_path = find_fixed_moving_paths(
        pair_dir
    )

    fixed_np = load_volume(fixed_path)
    moving_np = load_volume(moving_path)

    fixed_tensor = torch.from_numpy(
        fixed_np
    ).unsqueeze(0).unsqueeze(0).to(
        DEVICE,
        dtype=torch.float32,
    )

    moving_tensor = torch.from_numpy(
        moving_np
    ).unsqueeze(0).unsqueeze(0).to(
        DEVICE,
        dtype=torch.float32,
    )

    moving_bands = analysis(moving_tensor)
    fixed_bands = analysis(fixed_tensor)

    flow_low = model(
        moving_bands,
        fixed_bands,
    )

    flow_full = low_dvf_to_full_trilinear(
        flow_low
    )

    moved_tensor = transformer_full(
        moving_tensor,
        flow_full,
    )

    moved_np = moved_tensor[0, 0].cpu().numpy()
    flow_np = flow_full[0].cpu().numpy()

    fixed_body = make_body_mask(fixed_np)
    moving_body = make_body_mask(moving_np)
    moved_body = make_body_mask(moved_np)

    fixed_lung = make_lung_mask(fixed_np)
    moving_lung = make_lung_mask(moving_np)

    moved_lung = warp_mask_nearest(
        moving_lung,
        flow_full,
    )

    jacobian = jacobian_determinant(flow_np)

    valid_body = (
        fixed_body
        & valid_reference_mask(
            flow_full,
            margin=0,
        )
    )

    interior_body = binary_erosion(
        fixed_body,
        iterations=INTERIOR_MARGIN_VOXELS,
    ).astype(bool)

    interior_valid_body = (
        interior_body
        & valid_reference_mask(
            flow_full,
            margin=INTERIOR_MARGIN_VOXELS,
        )
    )

    z_window = np.zeros_like(
        fixed_body,
        dtype=bool,
    )

    z0 = max(0, Z_START)
    z1 = min(FULL_SIZE[0] - 1, Z_END)

    z_window[z0:z1 + 1] = True

    interior_valid_body_z64 = (
        interior_valid_body
        & z_window
    )

    mse_before = np.mean(
        (moving_np - fixed_np) ** 2
    )

    mse_after = np.mean(
        (moved_np - fixed_np) ** 2
    )

    ms_ssim_value, fsim_value = compute_ms_ssim_fsim(
        fixed_np,
        moved_np,
    )

    dice_before, jaccard_before = dice_jaccard(
        fixed_body,
        moving_body,
    )

    dice_after, jaccard_after = dice_jaccard(
        fixed_body,
        moved_body,
    )

    result = {
        "model": MODEL_NAME,
        "pair": pair_dir.name,
        "fixed_file": fixed_path.name,
        "moving_file": moving_path.name,

        "dice_before": dice_before,
        "dice_after": dice_after,
        "jaccard_before": jaccard_before,
        "jaccard_after": jaccard_after,

        "ncc_before": compute_ncc(
            fixed_np,
            moving_np,
        ),
        "ncc_after": compute_ncc(
            fixed_np,
            moved_np,
        ),

        "rmse_hu_before": float(
            np.sqrt(mse_before)
            * (HU_MAX - HU_MIN)
        ),
        "rmse_hu_after": float(
            np.sqrt(mse_after)
            * (HU_MAX - HU_MIN)
        ),

        "ssim_after": compute_mean_ssim(
            fixed_np,
            moved_np,
        ),

        "ms_ssim_after": ms_ssim_value,
        "fsim_after": fsim_value,

        # 従来どおり：全画素
        "raw_full_folding_percent": float(
            np.mean(jacobian <= 0.0) * 100.0
        ),

        # Body内かつMoving参照座標が画像内
        "valid_body_folding_percent": folding_percent(
            jacobian,
            valid_body,
        ),

        # 体表・画像端から5 voxelを除外
        "interior_valid_body_folding_percent": (
            folding_percent(
                jacobian,
                interior_valid_body,
            )
        ),

        # z=60–68に限定
        "interior_valid_body_folding_z60_to_z68_percent": (
            folding_percent(
                jacobian,
                interior_valid_body_z64,
            )
        ),

        "jacobian_min": float(jacobian.min()),

        "lung_dice_after": dice_jaccard(
            fixed_lung,
            moved_lung,
        )[0],

        "lung_folding_percent": folding_percent(
            jacobian,
            fixed_lung,
        ),

        "valid_body_fraction_percent": float(
            100.0
            * valid_body.sum()
            / max(fixed_body.sum(), 1)
        ),

        "interior_valid_body_fraction_percent": float(
            100.0
            * interior_valid_body.sum()
            / max(fixed_body.sum(), 1)
        ),

        "flow_magnitude_mean_voxel": float(
            np.sqrt(
                np.sum(flow_np ** 2, axis=0)
            ).mean()
        ),
    }

    del fixed_tensor
    del moving_tensor
    del moving_bands
    del fixed_bands
    del flow_low
    del flow_full
    del moved_tensor

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result

In [8]:
# ------------------------------------------------------------
# 7. 全101ペア評価
# ------------------------------------------------------------

pair_dirs = sorted(
    [
        path
        for path in TEST_DATA_ROOT.iterdir()
        if path.is_dir()
        and path.name.lower().startswith("pair")
    ],
    key=natural_sort_key,
)

if len(pair_dirs) == 0:
    raise FileNotFoundError(
        f"pairフォルダがありません:\n{TEST_DATA_ROOT}"
    )

print(f"\n評価pair数: {len(pair_dirs)}")

rows = []

for index, pair_dir in enumerate(
    tqdm(pair_dirs, desc="Fine-tuned Coarse-only evaluation"),
    start=1,
):
    try:
        result = evaluate_pair(pair_dir)
        rows.append(result)

        print(
            f"[{index:03d}/{len(pair_dirs):03d}] "
            f"{pair_dir.name} | "
            f"Dice={result['dice_after']:.5f} | "
            f"NCC={result['ncc_after']:.5f} | "
            f"rawFold={result['raw_full_folding_percent']:.4f}% | "
            f"interiorFold={result['interior_valid_body_folding_percent']:.4f}%"
        )

    except Exception as error:
        print(
            f"[Skip] {pair_dir.name}: {repr(error)}"
        )

評価pair数: 101

Fine-tuned Coarse-only evaluation:   0%|          | 0/101 [00:00<?, ?it/s]

[001/101] pair1 | Dice=0.99536 | NCC=0.99326 | rawFold=0.7392% | interiorFold=0.2593%
[002/101] pair2 | Dice=0.99412 | NCC=0.99223 | rawFold=0.4451% | interiorFold=0.7323%
[003/101] pair3 | Dice=0.99406 | NCC=0.99182 | rawFold=0.3438% | interiorFold=0.2528%
[004/101] pair4 | Dice=0.99477 | NCC=0.99322 | rawFold=0.0746% | interiorFold=0.1718%
[005/101] pair5 | Dice=0.99595 | NCC=0.99295 | rawFold=0.1501% | interiorFold=0.3148%
[006/101] pair6 | Dice=0.99624 | NCC=0.99375 | rawFold=0.1746% | interiorFold=0.2364%
[007/101] pair7 | Dice=0.99595 | NCC=0.99323 | rawFold=0.7353% | interiorFold=0.1744%
[008/101] pair8 | Dice=0.99589 | NCC=0.99359 | rawFold=0.7976% | interiorFold=0.2013%
[009/101] pair9 | Dice=0.99509 | NCC=0.99286 | rawFold=0.2607% | interiorFold=0.3780%
[010/101] pair10 | Dice=0.99438 | NCC=0.99227 | rawFold=0.3835% | interiorFold=0.7612%
[011/101] pair11 | Dice=0.99522 | NCC=0.99208 | rawFold=0.4330% | interiorFold=0.1095%
[012/101] pair12 | Dice=0.99373 | NCC=0.99194 | rawFold=2.2219% | interiorFold=0.2501%
[013/101] pair13 | Dice=0.99507 | NCC=0.99495 | rawFold=0.0624% | interiorFold=0.0252%
[014/101] pair14 | Dice=0.99493 | NCC=0.99429 | rawFold=0.0683% | interiorFold=0.1336%
[015/101] pair15 | Dice=0.99502 | NCC=0.99102 | rawFold=0.3514% | interiorFold=0.6671%
[016/101] pair16 | Dice=0.99606 | NCC=0.99290 | rawFold=0.1958% | interiorFold=0.3538%
[017/101] pair17 | Dice=0.99520 | NCC=0.99002 | rawFold=1.0758% | interiorFold=0.5648%
[018/101] pair18 | Dice=0.99296 | NCC=0.98389 | rawFold=3.1448% | interiorFold=2.3857%
[019/101] pair19 | Dice=0.99512 | NCC=0.99236 | rawFold=0.1392% | interiorFold=0.2275%
[020/101] pair20 | Dice=0.99466 | NCC=0.98777 | rawFold=0.9409% | interiorFold=1.6097%
[021/101] pair21 | Dice=0.99574 | NCC=0.99360 | rawFold=0.0902% | interiorFold=0.1216%
[022/101] pair22 | Dice=0.99615 | NCC=0.99063 | rawFold=0.3474% | interiorFold=0.7130%
[023/101] pair23 | Dice=0.99579 | NCC=0.99299 | rawFold=0.2267% | interiorFold=0.2835%
[024/101] pair24 | Dice=0.99461 | NCC=0.99510 | rawFold=0.0709% | interiorFold=0.1549%
[025/101] pair25 | Dice=0.99412 | NCC=0.99325 | rawFold=0.2797% | interiorFold=0.4081%
[026/101] pair26 | Dice=0.99441 | NCC=0.99157 | rawFold=0.3667% | interiorFold=0.8305%
[027/101] pair27 | Dice=0.99522 | NCC=0.98983 | rawFold=0.2926% | interiorFold=0.6342%
[028/101] pair28 | Dice=0.99414 | NCC=0.99399 | rawFold=0.0728% | interiorFold=0.1279%
[029/101] pair29 | Dice=0.99477 | NCC=0.98992 | rawFold=0.4164% | interiorFold=0.8468%
[030/101] pair30 | Dice=0.99317 | NCC=0.99200 | rawFold=0.3442% | interiorFold=0.8454%
[031/101] pair31 | Dice=0.99351 | NCC=0.98994 | rawFold=1.6717% | interiorFold=0.6650%
[032/101] pair32 | Dice=0.99385 | NCC=0.99173 | rawFold=2.8277% | interiorFold=0.1361%
[033/101] pair33 | Dice=0.99467 | NCC=0.99193 | rawFold=0.7890% | interiorFold=0.1638%
[034/101] pair34 | Dice=0.99053 | NCC=0.98498 | rawFold=4.2725% | interiorFold=1.6404%
[035/101] pair35 | Dice=0.99558 | NCC=0.99485 | rawFold=0.0773% | interiorFold=0.1249%
[036/101] pair36 | Dice=0.99413 | NCC=0.98864 | rawFold=0.9810% | interiorFold=1.9221%
[037/101] pair37 | Dice=0.99259 | NCC=0.98642 | rawFold=2.3571% | interiorFold=2.3127%
[038/101] pair38 | Dice=0.99352 | NCC=0.98972 | rawFold=0.5200% | interiorFold=1.1942%
[039/101] pair39 | Dice=0.99420 | NCC=0.98915 | rawFold=0.6896% | interiorFold=1.9331%
[040/101] pair40 | Dice=0.99201 | NCC=0.99075 | rawFold=1.2718% | interiorFold=0.4090%
[041/101] pair41 | Dice=0.99484 | NCC=0.99498 | rawFold=0.0429% | interiorFold=0.1038%
[042/101] pair42 | Dice=0.99534 | NCC=0.99396 | rawFold=0.1480% | interiorFold=0.2743%
[043/101] pair43 | Dice=0.99419 | NCC=0.99070 | rawFold=1.2856% | interiorFold=0.4873%
[044/101] pair44 | Dice=0.99469 | NCC=0.98889 | rawFold=2.0445% | interiorFold=0.7767%
[045/101] pair45 | Dice=0.99630 | NCC=0.99560 | rawFold=0.0901% | interiorFold=0.1141%
[046/101] pair46 | Dice=0.98720 | NCC=0.98425 | rawFold=1.5662% | interiorFold=0.3155%
[047/101] pair47 | Dice=0.99488 | NCC=0.99075 | rawFold=1.5965% | interiorFold=0.4103%
[048/101] pair48 | Dice=0.99423 | NCC=0.98947 | rawFold=1.7822% | interiorFold=0.2991%
[049/101] pair49 | Dice=0.99409 | NCC=0.99071 | rawFold=2.9339% | interiorFold=0.2784%
[050/101] pair50 | Dice=0.99400 | NCC=0.98914 | rawFold=1.6903% | interiorFold=0.4808%
[051/101] pair51 | Dice=0.99280 | NCC=0.98738 | rawFold=3.8274% | interiorFold=0.6933%
[052/101] pair52 | Dice=0.99427 | NCC=0.99176 | rawFold=0.1009% | interiorFold=0.2124%
[053/101] pair53 | Dice=0.99410 | NCC=0.99247 | rawFold=0.7192% | interiorFold=0.3078%
[054/101] pair54 | Dice=0.99283 | NCC=0.98756 | rawFold=0.8757% | interiorFold=0.6808%
[055/101] pair55 | Dice=0.99451 | NCC=0.99149 | rawFold=1.0315% | interiorFold=0.3382%
[056/101] pair56 | Dice=0.99529 | NCC=0.99252 | rawFold=0.1685% | interiorFold=0.2360%
[057/101] pair57 | Dice=0.99318 | NCC=0.98797 | rawFold=0.8111% | interiorFold=0.8605%
[058/101] pair58 | Dice=0.99385 | NCC=0.98938 | rawFold=0.5280% | interiorFold=0.5503%
[059/101] pair59 | Dice=0.99303 | NCC=0.98879 | rawFold=0.6640% | interiorFold=0.6539%
[060/101] pair60 | Dice=0.99446 | NCC=0.99123 | rawFold=0.4676% | interiorFold=0.6072%
[061/101] pair61 | Dice=0.99131 | NCC=0.98582 | rawFold=3.6237% | interiorFold=2.1181%
[062/101] pair62 | Dice=0.99332 | NCC=0.98960 | rawFold=2.4666% | interiorFold=0.5386%
[063/101] pair63 | Dice=0.99572 | NCC=0.99349 | rawFold=0.1089% | interiorFold=0.1594%
[064/101] pair64 | Dice=0.99573 | NCC=0.99450 | rawFold=0.0451% | interiorFold=0.0895%
[065/101] pair65 | Dice=0.99564 | NCC=0.99460 | rawFold=0.1078% | interiorFold=0.1278%
[066/101] pair66 | Dice=0.99286 | NCC=0.99019 | rawFold=2.3307% | interiorFold=0.4856%
[067/101] pair67 | Dice=0.99508 | NCC=0.99044 | rawFold=0.7997% | interiorFold=0.3298%
[068/101] pair68 | Dice=0.99423 | NCC=0.99161 | rawFold=0.3373% | interiorFold=0.4725%
[069/101] pair69 | Dice=0.99280 | NCC=0.99221 | rawFold=0.3789% | interiorFold=0.4747%
[070/101] pair70 | Dice=0.99367 | NCC=0.99338 | rawFold=0.1854% | interiorFold=0.2305%
[071/101] pair71 | Dice=0.99506 | NCC=0.99410 | rawFold=0.2219% | interiorFold=0.2200%
[072/101] pair72 | Dice=0.97208 | NCC=0.95688 | rawFold=3.1041% | interiorFold=0.8471%
[073/101] pair73 | Dice=0.99402 | NCC=0.98997 | rawFold=3.0226% | interiorFold=0.5305%
[074/101] pair74 | Dice=0.99552 | NCC=0.99316 | rawFold=0.7279% | interiorFold=0.4334%
[075/101] pair75 | Dice=0.99449 | NCC=0.99328 | rawFold=0.6680% | interiorFold=0.1559%
[076/101] pair76 | Dice=0.99497 | NCC=0.99308 | rawFold=0.6020% | interiorFold=0.0283%
[077/101] pair77 | Dice=0.93397 | NCC=0.90644 | rawFold=3.8660% | interiorFold=1.2583%
[078/101] pair78 | Dice=0.93544 | NCC=0.90444 | rawFold=4.8329% | interiorFold=2.3937%
[079/101] pair79 | Dice=0.93059 | NCC=0.90235 | rawFold=3.6938% | interiorFold=2.2763%
[080/101] pair80 | Dice=0.91906 | NCC=0.88443 | rawFold=3.7919% | interiorFold=1.5268%
[081/101] pair81 | Dice=0.99130 | NCC=0.98779 | rawFold=1.0777% | interiorFold=1.3181%
[082/101] pair82 | Dice=0.98968 | NCC=0.98789 | rawFold=0.5573% | interiorFold=1.1948%
[083/101] pair83 | Dice=0.99130 | NCC=0.98712 | rawFold=0.9069% | interiorFold=1.4692%
[084/101] pair84 | Dice=0.99428 | NCC=0.98918 | rawFold=0.7462% | interiorFold=1.7462%
[085/101] pair85 | Dice=0.99607 | NCC=0.99002 | rawFold=0.7723% | interiorFold=1.5572%
[086/101] pair86 | Dice=0.99222 | NCC=0.98751 | rawFold=0.5736% | interiorFold=1.0638%
[087/101] pair87 | Dice=0.99566 | NCC=0.99241 | rawFold=0.2334% | interiorFold=0.4638%
[088/101] pair88 | Dice=0.99645 | NCC=0.99332 | rawFold=0.3192% | interiorFold=0.2270%
[089/101] pair89 | Dice=0.98818 | NCC=0.98169 | rawFold=4.4749% | interiorFold=1.2425%
[090/101] pair90 | Dice=0.98143 | NCC=0.97023 | rawFold=4.7187% | interiorFold=1.9294%
[091/101] pair91 | Dice=0.99350 | NCC=0.99075 | rawFold=0.2897% | interiorFold=0.6481%
[092/101] pair92 | Dice=0.99430 | NCC=0.99064 | rawFold=0.3640% | interiorFold=0.7802%
[093/101] pair93 | Dice=0.99610 | NCC=0.99545 | rawFold=0.0325% | interiorFold=0.0874%
[094/101] pair94 | Dice=0.99472 | NCC=0.99050 | rawFold=0.9507% | interiorFold=0.4765%
[095/101] pair95 | Dice=0.99513 | NCC=0.99292 | rawFold=1.2668% | interiorFold=0.3098%
[096/101] pair96 | Dice=0.99492 | NCC=0.99302 | rawFold=0.3869% | interiorFold=0.3215%
[097/101] pair97 | Dice=0.99555 | NCC=0.99348 | rawFold=0.2694% | interiorFold=0.5707%
[098/101] pair98 | Dice=0.99471 | NCC=0.99401 | rawFold=0.1344% | interiorFold=0.1836%
[099/101] pair99 | Dice=0.99578 | NCC=0.99160 | rawFold=0.2235% | interiorFold=0.3608%
[100/101] pair100 | Dice=0.99521 | NCC=0.99265 | rawFold=0.1478% | interiorFold=0.2897%
[101/101] pair101 | Dice=0.99563 | NCC=0.99415 | rawFold=0.2172% | interiorFold=0.2457%

In [9]:

# ------------------------------------------------------------
# 8. Pair-wise CSV
# ------------------------------------------------------------

pairwise_df = pd.DataFrame(rows)

pairwise_csv = (
    EVAL_DIR
    / "pairwise_metrics_finetuned_coarse_only.csv"
)

pairwise_df.to_csv(
    pairwise_csv,
    index=False,
    encoding="utf-8-sig",
)

display(pairwise_df.round(6))

print("\nPair-wise CSV:")
print(pairwise_csv)

,model,pair,fixed_file,moving_file,dice_before,dice_after,jaccard_before,jaccard_after,ncc_before,ncc_after,...,raw_full_folding_percent,valid_body_folding_percent,interior_valid_body_folding_percent,interior_valid_body_folding_z60_to_z68_percent,jacobian_min,lung_dice_after,lung_folding_percent,valid_body_fraction_percent,interior_valid_body_fraction_percent,flow_magnitude_mean_voxel
0,30k_coarse_only_finetuned,pair1,registered_masked_A_MIC00197_2018_0428.npz,fixed_masked_B_MIC00197_2019_0406.npz,0.961797,0.995362,0.926405,0.990766,0.928469,0.993257,...,0.739229,0.300952,0.259330,0.008706,-3.709836,0.893092,0.118460,99.571015,83.405730,1.348287
1,30k_coarse_only_finetuned,pair2,registered_masked_A_MIC00761_2019_0727.npz,fixed_masked_B_MIC00761_2020_0926.npz,0.981110,0.994116,0.962920,0.988301,0.962952,0.992235,...,0.445092,0.848955,0.732283,0.069298,-5.062313,0.896702,0.002335,99.745335,82.743739,1.196022
2,30k_coarse_only_finetuned,pair3,registered_masked_A_MIC03568_2018_0825.npz,fixed_masked_B_MIC03568_2019_0824.npz,0.963118,0.994057,0.928860,0.988184,0.928717,0.991821,...,0.343764,0.243183,0.252827,0.132985,-3.023296,0.842017,0.047285,99.344100,82.652642,1.317584
3,30k_coarse_only_finetuned,pair4,registered_masked_A_MIC03568_2018_0825.npz,fixed_masked_B_MIC03568_2020_0829.npz,0.982659,0.994768,0.965908,0.989591,0.957978,0.993216,...,0.074601,0.166762,0.171781,0.028936,-1.250471,0.843378,0.008412,99.813316,82.595646,1.205959
4,30k_coarse_only_finetuned,pair5,registered_masked_A_MIC03568_2019_0824.npz,fixed_masked_B_MIC03568_2020_0829.npz,0.986525,0.995950,0.973408,0.991932,0.959973,0.992949,...,0.150120,0.325566,0.314843,0.151760,-1.851350,0.823556,0.025732,99.900783,82.415131,1.382915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,30k_coarse_only_finetuned,pair97,registered_masked_A_MIC45438_2019_0903.npz,fixed_masked_B_MIC45438_2020_0824.npz,0.979977,0.995550,0.960741,0.991139,0.947270,0.993477,...,0.269413,0.547465,0.570696,0.032274,-1.863317,0.772483,0.703898,99.826144,82.742414,1.739092
97,30k_coarse_only_finetuned,pair98,registered_masked_A_MIC52743_2018_1213.npz,fixed_masked_B_MIC52743_2020_0125.npz,0.978022,0.994715,0.956990,0.989485,0.952752,0.994009,...,0.134385,0.250556,0.183615,0.066265,-2.327193,0.865215,0.032687,99.850940,83.118550,1.474429
98,30k_coarse_only_finetuned,pair99,registered_masked_A_MIC53652_2019_1213.npz,fixed_masked_B_MIC53652_2020_1219.npz,0.981859,0.995778,0.964364,0.991592,0.947066,0.991595,...,0.223482,0.399139,0.360772,0.228126,-3.746541,0.836289,0.086755,99.655327,83.620737,1.739125
99,30k_coarse_only_finetuned,pair100,registered_masked_A_MIC53770_2018_1128.npz,fixed_masked_B_MIC53770_2019_1111.npz,0.980435,0.995213,0.961621,0.990471,0.954214,0.992648,...,0.147796,0.323363,0.289747,0.003718,-3.644271,0.928089,0.102263,99.434115,83.265800,1.289984
100,30k_coarse_only_finetuned,pair101,registered_masked_A_MIC53945_2019_0604.npz,fixed_masked_B_MIC53945_2020_0515.npz,0.980744,0.995632,0.962215,0.991302,0.961095,0.994151,...,0.217152,0.272553,0.245696,0.128330,-4.703747,0.895058,0.023368,99.863084,83.298825,1.244199

Pair-wise CSV:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_finetuned_30k\pairwise_metrics_finetuned_coarse_only.csv

In [10]:
# ------------------------------------------------------------
# 9. 平均表
# ------------------------------------------------------------

if len(pairwise_df) == 0:
    raise RuntimeError(
        "評価成功pairが0件です。"
    )

raw_worst = pairwise_df.loc[
    pairwise_df[
        "raw_full_folding_percent"
    ].idxmax()
]

valid_worst = pairwise_df.loc[
    pairwise_df[
        "valid_body_folding_percent"
    ].idxmax()
]

interior_worst = pairwise_df.loc[
    pairwise_df[
        "interior_valid_body_folding_percent"
    ].idxmax()
]

z64_worst = pairwise_df.loc[
    pairwise_df[
        "interior_valid_body_folding_z60_to_z68_percent"
    ].idxmax()
]

summary_df = pd.DataFrame(
    [
        {
            "model": MODEL_NAME,
            "n_pairs": int(len(pairwise_df)),

            "dice_before_mean": pairwise_df[
                "dice_before"
            ].mean(),
            "dice_after_mean": pairwise_df[
                "dice_after"
            ].mean(),
            "jaccard_after_mean": pairwise_df[
                "jaccard_after"
            ].mean(),

            "ncc_before_mean": pairwise_df[
                "ncc_before"
            ].mean(),
            "ncc_after_mean": pairwise_df[
                "ncc_after"
            ].mean(),

            "rmse_hu_before_mean": pairwise_df[
                "rmse_hu_before"
            ].mean(),
            "rmse_hu_after_mean": pairwise_df[
                "rmse_hu_after"
            ].mean(),

            "ssim_after_mean": pairwise_df[
                "ssim_after"
            ].mean(),
            "ms_ssim_after_mean": pairwise_df[
                "ms_ssim_after"
            ].mean(),
            "fsim_after_mean": pairwise_df[
                "fsim_after"
            ].mean(),

            "raw_full_folding_mean_percent": pairwise_df[
                "raw_full_folding_percent"
            ].mean(),
            "raw_full_folding_max_percent": pairwise_df[
                "raw_full_folding_percent"
            ].max(),
            "raw_full_worst_pair": raw_worst["pair"],

            "valid_body_folding_mean_percent": pairwise_df[
                "valid_body_folding_percent"
            ].mean(),
            "valid_body_folding_max_percent": pairwise_df[
                "valid_body_folding_percent"
            ].max(),
            "valid_body_worst_pair": valid_worst["pair"],

            "interior_valid_body_folding_mean_percent": pairwise_df[
                "interior_valid_body_folding_percent"
            ].mean(),
            "interior_valid_body_folding_max_percent": pairwise_df[
                "interior_valid_body_folding_percent"
            ].max(),
            "interior_valid_body_worst_pair": interior_worst["pair"],

            "interior_valid_body_folding_z60_to_z68_mean_percent": (
                pairwise_df[
                    "interior_valid_body_folding_z60_to_z68_percent"
                ].mean()
            ),
            "interior_valid_body_folding_z60_to_z68_max_percent": (
                pairwise_df[
                    "interior_valid_body_folding_z60_to_z68_percent"
                ].max()
            ),
            "interior_valid_body_folding_z60_to_z68_worst_pair": (
                z64_worst["pair"]
            ),

            "lung_dice_after_mean": pairwise_df[
                "lung_dice_after"
            ].mean(),
            "lung_folding_mean_percent": pairwise_df[
                "lung_folding_percent"
            ].mean(),

            "flow_magnitude_mean_voxel": pairwise_df[
                "flow_magnitude_mean_voxel"
            ].mean(),
        }
    ]
)

summary_csv = (
    EVAL_DIR
    / "summary_metrics_finetuned_coarse_only.csv"
)

summary_df.to_csv(
    summary_csv,
    index=False,
    encoding="utf-8-sig",
)

print("\n================ FINAL SUMMARY ================\n")
display(summary_df.round(6))

print("\nSummary CSV:")
print(summary_csv)

print("\nCompleted.")

================ FINAL SUMMARY ================

,model,n_pairs,dice_before_mean,dice_after_mean,jaccard_after_mean,ncc_before_mean,ncc_after_mean,rmse_hu_before_mean,rmse_hu_after_mean,ssim_after_mean,...,valid_body_worst_pair,interior_valid_body_folding_mean_percent,interior_valid_body_folding_max_percent,interior_valid_body_worst_pair,interior_valid_body_folding_z60_to_z68_mean_percent,interior_valid_body_folding_z60_to_z68_max_percent,interior_valid_body_folding_z60_to_z68_worst_pair,lung_dice_after_mean,lung_folding_mean_percent,flow_magnitude_mean_voxel
0,30k_coarse_only_finetuned,101,0.959418,0.991369,0.983194,0.920009,0.987036,411.771446,154.169764,0.910547,...,pair79,0.644943,2.393665,pair78,0.282361,3.237829,pair90,0.790941,0.531124,1.746876

Summary CSV:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_finetuned_30k\summary_metrics_finetuned_coarse_only.csv

Completed.

In [11]:
display(summary_df.T)

                                                                            0
model                                               30k_coarse_only_finetuned
n_pairs                                                                   101
dice_before_mean                                                     0.959418
dice_after_mean                                                      0.991369
jaccard_after_mean                                                   0.983194
ncc_before_mean                                                      0.920009
ncc_after_mean                                                       0.987036
rmse_hu_before_mean                                                411.771446
rmse_hu_after_mean                                                 154.169764
ssim_after_mean                                                      0.910547
ms_ssim_after_mean                                                   0.948334
fsim_after_mean                                                      0.941367
raw_full_folding_mean_percent                                        1.056003
raw_full_folding_max_percent                                           4.8329
raw_full_worst_pair                                                    pair78
valid_body_folding_mean_percent                                      0.733549
valid_body_folding_max_percent                                       2.983022
valid_body_worst_pair                                                  pair79
interior_valid_body_folding_mean_percent                             0.644943
interior_valid_body_folding_max_percent                              2.393665
interior_valid_body_worst_pair                                         pair78
interior_valid_body_folding_z60_to_z68_mean_per...                   0.282361
interior_valid_body_folding_z60_to_z68_max_percent                   3.237829
interior_valid_body_folding_z60_to_z68_worst_pair                      pair90
lung_dice_after_mean                                                 0.790941
lung_folding_mean_percent                                            0.531124
flow_magnitude_mean_voxel                                            1.746876

In [12]:
# ============================================================
# Fine-tuning後Coarse-only：Moving / Fixed / Moved画像を保存
# ============================================================

import gc
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import torch

# None: 全101ペアを保存
# 例 ["pair61", "pair78"] のようにすると指定pairだけ保存
PAIR_NAMES_TO_SAVE = None

# axial slice
SLICE_INDEX = 64

# 3DのMoved画像も保存するか
# Trueにするとファイル容量が大きくなるため、通常はFalse推奨
SAVE_MOVED_VOLUME_NPZ = False

required_names = [
    "TEST_DATA_ROOT",
    "EVAL_DIR",
    "DEVICE",
    "analysis",
    "model",
    "transformer_full",
    "low_dvf_to_full_trilinear",
    "load_volume",
    "find_fixed_moving_paths",
]

missing = [
    name
    for name in required_names
    if name not in globals()
]

if missing:
    raise NameError(
        "先にFine-tuning後モデルの完全評価セルを実行してください。\n"
        + ", ".join(missing)
    )

IMAGE_OUTPUT_DIR = EVAL_DIR / "axial_slice64_images"

IMAGE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

if PAIR_NAMES_TO_SAVE is None:
    pair_dirs = sorted(
        [
            path
            for path in TEST_DATA_ROOT.iterdir()
            if path.is_dir()
            and path.name.lower().startswith("pair")
        ],
        key=natural_sort_key,
    )
else:
    pair_dirs = [
        TEST_DATA_ROOT / pair_name
        for pair_name in PAIR_NAMES_TO_SAVE
    ]

print("保存pair数 :", len(pair_dirs))
print("保存先     :", IMAGE_OUTPUT_DIR)


@torch.no_grad()
def infer_moved_image(
    fixed_np,
    moving_np,
):
    fixed_tensor = torch.from_numpy(
        fixed_np.astype(np.float32)
    ).unsqueeze(0).unsqueeze(0).to(DEVICE)

    moving_tensor = torch.from_numpy(
        moving_np.astype(np.float32)
    ).unsqueeze(0).unsqueeze(0).to(DEVICE)

    moving_bands = analysis(moving_tensor)
    fixed_bands = analysis(fixed_tensor)

    flow_low = model(
        moving_bands,
        fixed_bands,
    )

    flow_full = low_dvf_to_full_trilinear(
        flow_low
    )

    moved_tensor = transformer_full(
        moving_tensor,
        flow_full,
    )

    moved_np = moved_tensor[
        0,
        0,
    ].cpu().numpy()

    del fixed_tensor
    del moving_tensor
    del moving_bands
    del fixed_bands
    del flow_low
    del flow_full
    del moved_tensor

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return moved_np


for index, pair_dir in enumerate(
    pair_dirs,
    start=1,
):
    if not pair_dir.is_dir():
        print(f"[Skip] pairフォルダなし: {pair_dir}")
        continue

    try:
        fixed_path, moving_path = find_fixed_moving_paths(
            pair_dir
        )

        fixed_np = load_volume(fixed_path)
        moving_np = load_volume(moving_path)

        if not (
            0 <= SLICE_INDEX < fixed_np.shape[0]
        ):
            raise ValueError(
                f"slice={SLICE_INDEX} が範囲外です"
            )

        moved_np = infer_moved_image(
            fixed_np=fixed_np,
            moving_np=moving_np,
        )

        moving_slice = moving_np[SLICE_INDEX]
        fixed_slice = fixed_np[SLICE_INDEX]
        moved_slice = moved_np[SLICE_INDEX]

        difference = np.abs(
            fixed_slice - moved_slice
        )

        vmin, vmax = np.percentile(
            np.concatenate(
                [
                    moving_slice.ravel(),
                    fixed_slice.ravel(),
                    moved_slice.ravel(),
                ]
            ),
            [1, 99],
        )

        diff_max = np.percentile(
            difference,
            99,
        )

        fig, axes = plt.subplots(
            1,
            4,
            figsize=(18, 5),
            constrained_layout=True,
        )

        images = [
            moving_slice,
            fixed_slice,
            moved_slice,
            difference,
        ]

        titles = [
            "Moving",
            "Fixed",
            "Fine-tuned Coarse-only Moved",
            "| Fixed − Moved |",
        ]

        for column, (
            image,
            title,
        ) in enumerate(
            zip(images, titles)
        ):
            if column < 3:
                axes[column].imshow(
                    image,
                    cmap="gray",
                    vmin=vmin,
                    vmax=vmax,
                )
            else:
                axes[column].imshow(
                    image,
                    cmap="magma",
                    vmin=0.0,
                    vmax=diff_max,
                )

            axes[column].set_title(
                title,
                fontsize=12,
            )

            axes[column].axis("off")

        fig.suptitle(
            f"{pair_dir.name} | axial slice {SLICE_INDEX} | "
            "Fine-tuned Coarse-only",
            fontsize=15,
        )

        png_path = (
            IMAGE_OUTPUT_DIR
            / (
                f"{pair_dir.name}_slice"
                f"{SLICE_INDEX:03d}_fine_tuned_coarse_only.png"
            )
        )

        fig.savefig(
            png_path,
            dpi=180,
            bbox_inches="tight",
        )

        plt.close(fig)

        if SAVE_MOVED_VOLUME_NPZ:
            npz_path = (
                IMAGE_OUTPUT_DIR
                / (
                    f"{pair_dir.name}_"
                    "fine_tuned_coarse_only_moved.npz"
                )
            )

            np.savez_compressed(
                npz_path,
                moved=moved_np.astype(np.float32),
            )

        print(
            f"[{index:03d}/{len(pair_dirs):03d}] "
            f"saved: {png_path.name}"
        )

    except Exception as error:
        print(
            f"[Skip] {pair_dir.name}: {repr(error)}"
        )

print("\n画像保存完了:")
print(IMAGE_OUTPUT_DIR)

保存pair数 : 101
保存先     : D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_finetuned_30k\axial_slice64_images
[001/101] saved: pair1_slice064_fine_tuned_coarse_only.png
[002/101] saved: pair2_slice064_fine_tuned_coarse_only.png
[003/101] saved: pair3_slice064_fine_tuned_coarse_only.png
[004/101] saved: pair4_slice064_fine_tuned_coarse_only.png
[005/101] saved: pair5_slice064_fine_tuned_coarse_only.png
[006/101] saved: pair6_slice064_fine_tuned_coarse_only.png
[007/101] saved: pair7_slice064_fine_tuned_coarse_only.png
[008/101] saved: pair8_slice064_fine_tuned_coarse_only.png
[009/101] saved: pair9_slice064_fine_tuned_coarse_only.png
[010/101] saved: pair10_slice064_fine_tuned_coarse_only.png
[011/101] saved: pair11_slice064_fine_tuned_coarse_only.png
[012/101] saved: pair12_slice064_fine_tuned_coarse_only.png
[013/101] saved: pair13_slice064_fine_tuned_coarse_only.png
[014/101] saved: pair14_slice064_fine_tuned_coarse_only.png
[015/101] saved: pair15_slice064_fine_tuned_coarse_only.png
[016/101] saved: pair16_slice064_fine_tuned_coarse_only.png
[017/101] saved: pair17_slice064_fine_tuned_coarse_only.png
[018/101] saved: pair18_slice064_fine_tuned_coarse_only.png
[019/101] saved: pair19_slice064_fine_tuned_coarse_only.png
[020/101] saved: pair20_slice064_fine_tuned_coarse_only.png
[021/101] saved: pair21_slice064_fine_tuned_coarse_only.png
[022/101] saved: pair22_slice064_fine_tuned_coarse_only.png
[023/101] saved: pair23_slice064_fine_tuned_coarse_only.png
[024/101] saved: pair24_slice064_fine_tuned_coarse_only.png
[025/101] saved: pair25_slice064_fine_tuned_coarse_only.png
[026/101] saved: pair26_slice064_fine_tuned_coarse_only.png
[027/101] saved: pair27_slice064_fine_tuned_coarse_only.png
[028/101] saved: pair28_slice064_fine_tuned_coarse_only.png
[029/101] saved: pair29_slice064_fine_tuned_coarse_only.png
[030/101] saved: pair30_slice064_fine_tuned_coarse_only.png
[031/101] saved: pair31_slice064_fine_tuned_coarse_only.png
[032/101] saved: pair32_slice064_fine_tuned_coarse_only.png
[033/101] saved: pair33_slice064_fine_tuned_coarse_only.png
[034/101] saved: pair34_slice064_fine_tuned_coarse_only.png
[035/101] saved: pair35_slice064_fine_tuned_coarse_only.png
[036/101] saved: pair36_slice064_fine_tuned_coarse_only.png
[037/101] saved: pair37_slice064_fine_tuned_coarse_only.png
[038/101] saved: pair38_slice064_fine_tuned_coarse_only.png
[039/101] saved: pair39_slice064_fine_tuned_coarse_only.png
[040/101] saved: pair40_slice064_fine_tuned_coarse_only.png
[041/101] saved: pair41_slice064_fine_tuned_coarse_only.png
[042/101] saved: pair42_slice064_fine_tuned_coarse_only.png
[043/101] saved: pair43_slice064_fine_tuned_coarse_only.png
[044/101] saved: pair44_slice064_fine_tuned_coarse_only.png
[045/101] saved: pair45_slice064_fine_tuned_coarse_only.png
[046/101] saved: pair46_slice064_fine_tuned_coarse_only.png
[047/101] saved: pair47_slice064_fine_tuned_coarse_only.png
[048/101] saved: pair48_slice064_fine_tuned_coarse_only.png
[049/101] saved: pair49_slice064_fine_tuned_coarse_only.png
[050/101] saved: pair50_slice064_fine_tuned_coarse_only.png
[051/101] saved: pair51_slice064_fine_tuned_coarse_only.png
[052/101] saved: pair52_slice064_fine_tuned_coarse_only.png
[053/101] saved: pair53_slice064_fine_tuned_coarse_only.png
[054/101] saved: pair54_slice064_fine_tuned_coarse_only.png
[055/101] saved: pair55_slice064_fine_tuned_coarse_only.png
[056/101] saved: pair56_slice064_fine_tuned_coarse_only.png
[057/101] saved: pair57_slice064_fine_tuned_coarse_only.png
[058/101] saved: pair58_slice064_fine_tuned_coarse_only.png
[059/101] saved: pair59_slice064_fine_tuned_coarse_only.png
[060/101] saved: pair60_slice064_fine_tuned_coarse_only.png
[061/101] saved: pair61_slice064_fine_tuned_coarse_only.png
[062/101] saved: pair62_slice064_fine_tuned_coarse_only.png
[063/101] saved: pair63_slice064_fine_tuned_coarse_only.png
[064/101] saved: pair64_slice064_fine_tuned_coarse_only.png
[065/101] saved: pair65_slice064_fine_tuned_coarse_only.png
[066/101] saved: pair66_slice064_fine_tuned_coarse_only.png
[067/101] saved: pair67_slice064_fine_tuned_coarse_only.png
[068/101] saved: pair68_slice064_fine_tuned_coarse_only.png
[069/101] saved: pair69_slice064_fine_tuned_coarse_only.png
[070/101] saved: pair70_slice064_fine_tuned_coarse_only.png
[071/101] saved: pair71_slice064_fine_tuned_coarse_only.png
[072/101] saved: pair72_slice064_fine_tuned_coarse_only.png
[073/101] saved: pair73_slice064_fine_tuned_coarse_only.png
[074/101] saved: pair74_slice064_fine_tuned_coarse_only.png
[075/101] saved: pair75_slice064_fine_tuned_coarse_only.png
[076/101] saved: pair76_slice064_fine_tuned_coarse_only.png
[077/101] saved: pair77_slice064_fine_tuned_coarse_only.png
[078/101] saved: pair78_slice064_fine_tuned_coarse_only.png
[079/101] saved: pair79_slice064_fine_tuned_coarse_only.png
[080/101] saved: pair80_slice064_fine_tuned_coarse_only.png
[081/101] saved: pair81_slice064_fine_tuned_coarse_only.png
[082/101] saved: pair82_slice064_fine_tuned_coarse_only.png
[083/101] saved: pair83_slice064_fine_tuned_coarse_only.png
[084/101] saved: pair84_slice064_fine_tuned_coarse_only.png
[085/101] saved: pair85_slice064_fine_tuned_coarse_only.png
[086/101] saved: pair86_slice064_fine_tuned_coarse_only.png
[087/101] saved: pair87_slice064_fine_tuned_coarse_only.png
[088/101] saved: pair88_slice064_fine_tuned_coarse_only.png
[089/101] saved: pair89_slice064_fine_tuned_coarse_only.png
[090/101] saved: pair90_slice064_fine_tuned_coarse_only.png
[091/101] saved: pair91_slice064_fine_tuned_coarse_only.png
[092/101] saved: pair92_slice064_fine_tuned_coarse_only.png
[093/101] saved: pair93_slice064_fine_tuned_coarse_only.png
[094/101] saved: pair94_slice064_fine_tuned_coarse_only.png
[095/101] saved: pair95_slice064_fine_tuned_coarse_only.png
[096/101] saved: pair96_slice064_fine_tuned_coarse_only.png
[097/101] saved: pair97_slice064_fine_tuned_coarse_only.png
[098/101] saved: pair98_slice064_fine_tuned_coarse_only.png
[099/101] saved: pair99_slice064_fine_tuned_coarse_only.png
[100/101] saved: pair100_slice064_fine_tuned_coarse_only.png
[101/101] saved: pair101_slice064_fine_tuned_coarse_only.png

画像保存完了:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_finetuned_30k\axial_slice64_images

In [13]:
# ============================================================
# Coarse-only LLL + IC fine-tuned model:
# TestData 101ペア 完全評価
#
# 評価:
# Dice / Jaccard / NCC / RMSE[HU] / SSIM / MS-SSIM / FSIM
# raw / valid-body / interior valid-body / z60-68 Folding
# Jacobian最小値 / lung Dice / lung Folding / 平均DVF大きさ
# IC MSE（学習時と同じ low-DVF 空間での逆写像整合性）
#
# 出力:
# - pairwise_metrics_coarse_only_lll_ic_finetuned.csv
# - summary_metrics_coarse_only_lll_ic_finetuned.csv
# - pair_images/*.png
# ============================================================

import os
os.environ["VXM_BACKEND"] = "pytorch"

from pathlib import Path
import re
import gc
import math
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

import voxelmorph as vxm

from scipy.ndimage import (
    binary_fill_holes,
    binary_opening,
    binary_erosion,
    label,
)
from skimage.metrics import structural_similarity
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")


# ------------------------------------------------------------
# 1. パス・基本設定
# ------------------------------------------------------------

TEST_DATA_ROOT = Path(
    r"D:\Saito\Data\TestData"
)

MODEL_PATH = Path(
    r"D:\Saito\fullres_trilinear_ic_beta1e3_80k"
    r"\coarse_only_lll_ic_finetune_30k"
    r"\model_coarse_only_lll_ic_finetuned_30k_final.pth"
)

EVAL_DIR = (
    MODEL_PATH.parent
    / "testdata_evaluation_coarse_only_lll_ic_finetuned_30k"
)

IMAGE_DIR = EVAL_DIR / "pair_images"

EVAL_DIR.mkdir(parents=True, exist_ok=True)
IMAGE_DIR.mkdir(parents=True, exist_ok=True)

MODEL_NAME = "30k_coarse_only_lll_ic_finetuned"

FULL_SIZE = (128, 256, 256)
LOW_SIZE = (64, 128, 128)

HU_MIN = -1024.0
HU_MAX = 3071.0

BODY_THRESHOLD = 0.10
INTERIOR_MARGIN_VOXELS = 5

Z_CENTER = 64
Z_RADIUS = 4
Z_START = Z_CENTER - Z_RADIUS
Z_END = Z_CENTER + Z_RADIUS

# True: 全101ペアの4-panel画像を保存
SAVE_ALL_PAIR_IMAGES = True

DEVICE = torch.device(
    "cuda:0"
    if torch.cuda.is_available()
    else "cpu"
)

if torch.cuda.is_available():
    torch.backends.cudnn.benchmark = True
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True

try:
    torch.set_float32_matmul_precision("high")
except AttributeError:
    pass

if not TEST_DATA_ROOT.is_dir():
    raise FileNotFoundError(
        f"TestDataが見つかりません:\n{TEST_DATA_ROOT}"
    )

if not MODEL_PATH.is_file():
    raise FileNotFoundError(
        f"Fine-tuning済み重みが見つかりません:\n{MODEL_PATH}"
    )

print("Device     :", DEVICE)
print("TestData   :", TEST_DATA_ROOT)
print("Model path :", MODEL_PATH)
print("Output dir :", EVAL_DIR)
print("Direction  : Moving -> Fixed")


# ------------------------------------------------------------
# 2. Haar解析・DVF変換・モデル
# ------------------------------------------------------------

class Haar3DAnalysis(nn.Module):

    def __init__(self):
        super().__init__()

        h_low = torch.tensor(
            [1.0, 1.0],
            dtype=torch.float32,
        ) / math.sqrt(2.0)

        h_high = torch.tensor(
            [1.0, -1.0],
            dtype=torch.float32,
        ) / math.sqrt(2.0)

        filters = []

        for z_filter in [h_low, h_high]:
            for y_filter in [h_low, h_high]:
                for x_filter in [h_low, h_high]:
                    kernel = (
                        z_filter[:, None, None]
                        * y_filter[None, :, None]
                        * x_filter[None, None, :]
                    )
                    filters.append(kernel)

        self.register_buffer(
            "weight",
            torch.stack(filters, dim=0).unsqueeze(1),
        )

    def forward(self, image):
        return F.conv3d(
            image,
            self.weight,
            stride=2,
            padding=0,
        )


def low_dvf_to_full_trilinear(flow_low):
    return F.interpolate(
        flow_low.float(),
        size=FULL_SIZE,
        mode="trilinear",
        align_corners=False,
    ) * 2.0


nb_features = [
    [32, 64, 64, 64, 64],
    [64, 64, 64, 64, 64, 32, 16, 16],
]


def create_single_voxelmorph():
    return vxm.networks.VxmDense_128_256_256(
        FULL_SIZE,
        nb_features,
        nb_features,
        int_steps=0,
    )


# ------------------------------------------------------------
# 3. 重み読込
# ------------------------------------------------------------

try:
    checkpoint = torch.load(
        MODEL_PATH,
        map_location="cpu",
        weights_only=False,
    )
except TypeError:
    checkpoint = torch.load(
        MODEL_PATH,
        map_location="cpu",
    )

state_dict = checkpoint.get(
    "model_state_dict",
    checkpoint,
)

state_dict = {
    key.replace("_orig_mod.", "", 1): value
    for key, value in state_dict.items()
}

analysis = Haar3DAnalysis().to(DEVICE).eval()

model = create_single_voxelmorph().to(DEVICE)
model.load_state_dict(state_dict, strict=True)
model.eval()

transformer_full = vxm.layers.SpatialTransformer(
    FULL_SIZE
).to(DEVICE).eval()

# IC MSE計算用：学習時と同じlow-DVF空間のTransformer
transformer_low = vxm.layers.SpatialTransformer(
    LOW_SIZE
).to(DEVICE).eval()

print("\nModel loading completed.")
print("Checkpoint epoch:", checkpoint.get("epoch", "unknown"))
print("Architecture    :", checkpoint.get("architecture", "unknown"))
print("Loss            :", checkpoint.get("loss_name", "unknown"))


# ------------------------------------------------------------
# 4. データ読込・ファイル探索
# ------------------------------------------------------------

def natural_sort_key(path):
    parts = re.findall(r"\d+", Path(path).name)
    return [int(value) for value in parts] if parts else [Path(path).name]


def load_volume(path):
    path = Path(path)

    if path.suffix.lower() == ".npy":
        volume = np.load(path)

    elif path.suffix.lower() == ".npz":
        archive = np.load(path)

        preferred_keys = [
            "image",
            "volume",
            "arr_0",
            "data",
        ]

        key = next(
            (
                candidate
                for candidate in preferred_keys
                if candidate in archive.files
            ),
            archive.files[0],
        )

        volume = archive[key]

    else:
        raise ValueError(f"未対応形式です: {path}")

    volume = np.asarray(volume).squeeze()

    if tuple(volume.shape) != FULL_SIZE:
        raise ValueError(
            f"shape={volume.shape}, expected={FULL_SIZE}\n{path}"
        )

    return volume.astype(np.float32)


def find_fixed_moving_paths(pair_dir):
    files = sorted(
        list(pair_dir.rglob("*.npz"))
        + list(pair_dir.rglob("*.npy")),
        key=natural_sort_key,
    )

    fixed_candidates = [
        path
        for path in files
        if (
            "fixed" in path.name.lower()
            or "target" in path.name.lower()
        )
    ]

    moving_candidates = [
        path
        for path in files
        if (
            "moving" in path.name.lower()
            or "move" in path.name.lower()
            or "source" in path.name.lower()
            or "registered" in path.name.lower()
        )
    ]

    if fixed_candidates and moving_candidates:
        return fixed_candidates[0], moving_candidates[0]

    raise FileNotFoundError(
        "Fixed / Moving画像を名前から特定できません。\n"
        f"{pair_dir}\n"
        f"検出ファイル: {[path.name for path in files]}"
    )


# ------------------------------------------------------------
# 5. 指標関数
# ------------------------------------------------------------

def compute_ncc(first, second):
    first = first.astype(np.float64)
    second = second.astype(np.float64)

    first = first - first.mean()
    second = second - second.mean()

    return float(
        np.sum(first * second)
        / (
            np.sqrt(
                np.sum(first ** 2)
                * np.sum(second ** 2)
            )
            + 1e-12
        )
    )


def make_body_mask(image):
    return binary_fill_holes(
        np.clip(image, 0.0, 1.0) > BODY_THRESHOLD
    ).astype(bool)


def keep_largest_components(mask, n_components=2):
    labeled, count = label(mask)

    if count == 0:
        return np.zeros_like(mask, dtype=bool)

    sizes = np.bincount(labeled.ravel())
    sizes[0] = 0

    selected = np.argsort(sizes)[-n_components:]

    return np.isin(labeled, selected)


def make_lung_mask(image):
    image_hu = (
        np.clip(image, 0.0, 1.0)
        * (HU_MAX - HU_MIN)
        + HU_MIN
    )

    body = make_body_mask(image)

    lung_candidate = (
        (image_hu >= -1000.0)
        & (image_hu <= -300.0)
        & body
    )

    lung_candidate = binary_opening(
        lung_candidate,
        iterations=1,
    )

    return keep_largest_components(
        lung_candidate,
        n_components=2,
    ).astype(bool)


def dice_jaccard(mask_a, mask_b):
    intersection = np.logical_and(mask_a, mask_b).sum()
    union = np.logical_or(mask_a, mask_b).sum()

    dice = (
        2.0 * intersection
        / (mask_a.sum() + mask_b.sum() + 1e-12)
    )

    jaccard = intersection / (union + 1e-12)

    return float(dice), float(jaccard)


def compute_mean_ssim(fixed, moved):
    values = []

    for z in range(fixed.shape[0]):
        values.append(
            structural_similarity(
                np.clip(fixed[z], 0.0, 1.0),
                np.clip(moved[z], 0.0, 1.0),
                data_range=1.0,
            )
        )

    return float(np.mean(values))


def compute_ms_ssim_fsim(fixed, moved):
    try:
        import piq
    except ImportError:
        return np.nan, np.nan

    fixed_tensor = torch.from_numpy(
        np.clip(fixed, 0.0, 1.0).astype(np.float32)
    ).unsqueeze(1).to(DEVICE)

    moved_tensor = torch.from_numpy(
        np.clip(moved, 0.0, 1.0).astype(np.float32)
    ).unsqueeze(1).to(DEVICE)

    ms_ssim_value = np.nan
    fsim_value = np.nan

    try:
        ms_ssim_value = piq.multi_scale_ssim(
            moved_tensor,
            fixed_tensor,
            data_range=1.0,
            reduction="mean",
        ).item()
    except Exception as error:
        print("MS-SSIM skipped:", repr(error))

    try:
        middle = fixed.shape[0] // 2

        fsim_value = piq.fsim(
            moved_tensor[middle:middle + 1],
            fixed_tensor[middle:middle + 1],
            data_range=1.0,
            chromatic=False,
            reduction="mean",
        ).item()

    except TypeError:
        fsim_value = piq.fsim(
            moved_tensor[middle:middle + 1],
            fixed_tensor[middle:middle + 1],
            data_range=1.0,
            reduction="mean",
        ).item()

    except Exception as error:
        print("FSIM skipped:", repr(error))

    del fixed_tensor
    del moved_tensor

    return ms_ssim_value, fsim_value


def jacobian_determinant(flow_np):
    uz, uy, ux = flow_np

    duz_dz, duz_dy, duz_dx = np.gradient(
        uz,
        edge_order=1,
    )

    duy_dz, duy_dy, duy_dx = np.gradient(
        uy,
        edge_order=1,
    )

    dux_dz, dux_dy, dux_dx = np.gradient(
        ux,
        edge_order=1,
    )

    j11 = 1.0 + duz_dz
    j12 = duz_dy
    j13 = duz_dx

    j21 = duy_dz
    j22 = 1.0 + duy_dy
    j23 = duy_dx

    j31 = dux_dz
    j32 = dux_dy
    j33 = 1.0 + dux_dx

    return (
        j11 * (j22 * j33 - j23 * j32)
        - j12 * (j21 * j33 - j23 * j31)
        + j13 * (j21 * j32 - j22 * j31)
    ).astype(np.float32)


def valid_reference_mask(flow_full, margin=0):
    _, _, depth, height, width = flow_full.shape

    z = torch.arange(
        depth,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, depth, 1, 1)

    y = torch.arange(
        height,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, 1, height, 1)

    x = torch.arange(
        width,
        device=flow_full.device,
        dtype=torch.float32,
    ).view(1, 1, 1, 1, width)

    sampled_z = z + flow_full[:, 0:1].float()
    sampled_y = y + flow_full[:, 1:2].float()
    sampled_x = x + flow_full[:, 2:3].float()

    margin = float(margin)

    valid = (
        (sampled_z >= margin)
        & (sampled_z <= float(depth - 1) - margin)
        & (sampled_y >= margin)
        & (sampled_y <= float(height - 1) - margin)
        & (sampled_x >= margin)
        & (sampled_x <= float(width - 1) - margin)
    )

    return valid[0, 0].cpu().numpy().astype(bool)


def warp_mask_nearest(mask_np, flow_full):
    mask_tensor = torch.from_numpy(
        mask_np.astype(np.float32)
    ).unsqueeze(0).unsqueeze(0).to(DEVICE)

    depth, height, width = FULL_SIZE

    z = torch.arange(
        depth,
        device=DEVICE,
        dtype=torch.float32,
    )

    y = torch.arange(
        height,
        device=DEVICE,
        dtype=torch.float32,
    )

    x = torch.arange(
        width,
        device=DEVICE,
        dtype=torch.float32,
    )

    zz, yy, xx = torch.meshgrid(
        z, y, x,
        indexing="ij",
    )

    grid = torch.stack(
        [zz, yy, xx],
        dim=0,
    ).unsqueeze(0)

    grid = grid + flow_full.float()

    grid[:, 0] = (
        2.0 * grid[:, 0] / max(depth - 1, 1) - 1.0
    )
    grid[:, 1] = (
        2.0 * grid[:, 1] / max(height - 1, 1) - 1.0
    )
    grid[:, 2] = (
        2.0 * grid[:, 2] / max(width - 1, 1) - 1.0
    )

    grid = grid.permute(
        0, 2, 3, 4, 1
    )[..., [2, 1, 0]]

    warped = F.grid_sample(
        mask_tensor,
        grid,
        mode="nearest",
        padding_mode="zeros",
        align_corners=True,
    )

    return warped[0, 0].cpu().numpy() > 0.5


def folding_percent(jacobian, mask):
    if mask.sum() == 0:
        return np.nan

    return float(
        np.mean(jacobian[mask] <= 0.0) * 100.0
    )


# ------------------------------------------------------------
# 6. IC MSE：学習時と同じ定義
# ------------------------------------------------------------

z_low = torch.arange(
    LOW_SIZE[0],
    device=DEVICE,
    dtype=torch.float32,
)

y_low = torch.arange(
    LOW_SIZE[1],
    device=DEVICE,
    dtype=torch.float32,
)

x_low = torch.arange(
    LOW_SIZE[2],
    device=DEVICE,
    dtype=torch.float32,
)

zz_low, yy_low, xx_low = torch.meshgrid(
    z_low,
    y_low,
    x_low,
    indexing="ij",
)

LOW_BASE_GRID = torch.stack(
    [zz_low, yy_low, xx_low],
    dim=0,
).unsqueeze(0)


def valid_mask_low(flow_low):
    position = LOW_BASE_GRID + flow_low.float()

    return (
        (position[:, 0] >= 0)
        & (position[:, 0] <= LOW_SIZE[0] - 1)
        & (position[:, 1] >= 0)
        & (position[:, 1] <= LOW_SIZE[1] - 1)
        & (position[:, 2] >= 0)
        & (position[:, 2] <= LOW_SIZE[2] - 1)
    )


def masked_vector_mse(vector_field, valid_mask):
    per_voxel_mse = (
        vector_field.float()
        .square()
        .mean(dim=1)
    )

    valid_values = per_voxel_mse[valid_mask]

    if valid_values.numel() == 0:
        return torch.tensor(
            float("nan"),
            device=DEVICE,
        )

    return valid_values.mean()


def inverse_consistency_mse(
    flow_m2f_low,
    flow_f2m_low,
):
    # φ_MF + φ_FM(x + φ_MF)
    flow_f2m_on_m2f = transformer_low(
        flow_f2m_low.float(),
        flow_m2f_low.float(),
    )

    residual_m2f = (
        flow_m2f_low.float()
        + flow_f2m_on_m2f
    )

    mse_m2f = masked_vector_mse(
        residual_m2f,
        valid_mask_low(flow_m2f_low),
    )

    # φ_FM + φ_MF(x + φ_FM)
    flow_m2f_on_f2m = transformer_low(
        flow_m2f_low.float(),
        flow_f2m_low.float(),
    )

    residual_f2m = (
        flow_f2m_low.float()
        + flow_m2f_on_f2m
    )

    mse_f2m = masked_vector_mse(
        residual_f2m,
        valid_mask_low(flow_f2m_low),
    )

    return 0.5 * (mse_m2f + mse_f2m)


# ------------------------------------------------------------
# 7. 画像保存
# ------------------------------------------------------------

def save_pair_image(
    pair_name,
    moving_np,
    fixed_np,
    moved_np,
    jacobian,
    result,
):
    z = min(
        max(Z_CENTER, 0),
        FULL_SIZE[0] - 1,
    )

    vmin, vmax = np.percentile(
        np.concatenate(
            [
                moving_np[z].ravel(),
                fixed_np[z].ravel(),
                moved_np[z].ravel(),
            ]
        ),
        [1, 99],
    )

    difference = np.abs(fixed_np[z] - moved_np[z])

    difference_max = max(
        np.percentile(difference, 99),
        1e-6,
    )

    fig, axes = plt.subplots(
        1,
        5,
        figsize=(24, 5),
        constrained_layout=True,
    )

    panels = [
        (
            moving_np[z],
            "Moving",
            "gray",
            vmin,
            vmax,
        ),
        (
            fixed_np[z],
            "Fixed",
            "gray",
            vmin,
            vmax,
        ),
        (
            moved_np[z],
            "Moved\nCoarse-only LLL IC",
            "gray",
            vmin,
            vmax,
        ),
        (
            difference,
            "|Fixed - Moved|",
            "hot",
            0.0,
            difference_max,
        ),
        (
            jacobian[z],
            "Jacobian determinant\nred contour: ≤ 0",
            "coolwarm",
            -1.0,
            3.0,
        ),
    ]

    for axis, (
        image,
        title,
        cmap,
        panel_vmin,
        panel_vmax,
    ) in zip(axes, panels):

        axis.imshow(
            image,
            cmap=cmap,
            vmin=panel_vmin,
            vmax=panel_vmax,
        )

        if title.startswith("Jacobian"):
            axis.contour(
                jacobian[z] <= 0.0,
                levels=[0.5],
                colors="red",
                linewidths=0.7,
            )

        axis.set_title(title)
        axis.axis("off")

    fig.suptitle(
        f"{pair_name} | z={z} | "
        f"Dice={result['dice_after']:.4f} | "
        f"NCC={result['ncc_after']:.4f} | "
        f"interior Fold="
        f"{result['interior_valid_body_folding_percent']:.4f}% | "
        f"IC MSE={result['ic_mse']:.6f}",
        fontsize=13,
    )

    output_path = IMAGE_DIR / f"{pair_name}_z{z:03d}.png"

    fig.savefig(
        output_path,
        dpi=160,
        bbox_inches="tight",
    )

    plt.close(fig)

    return str(output_path)


# ------------------------------------------------------------
# 8. 1ペア評価
# ------------------------------------------------------------

@torch.no_grad()
def evaluate_pair(pair_dir):
    fixed_path, moving_path = find_fixed_moving_paths(pair_dir)

    fixed_np = load_volume(fixed_path)
    moving_np = load_volume(moving_path)

    fixed_tensor = torch.from_numpy(
        fixed_np
    ).unsqueeze(0).unsqueeze(0).to(
        DEVICE,
        dtype=torch.float32,
    )

    moving_tensor = torch.from_numpy(
        moving_np
    ).unsqueeze(0).unsqueeze(0).to(
        DEVICE,
        dtype=torch.float32,
    )

    moving_bands = analysis(moving_tensor)
    fixed_bands = analysis(fixed_tensor)

    # Moving -> Fixed
    flow_m2f_low = model(
        moving_bands,
        fixed_bands,
    )

    flow_m2f_full = low_dvf_to_full_trilinear(
        flow_m2f_low
    )

    moved_tensor = transformer_full(
        moving_tensor,
        flow_m2f_full,
    )

    # Fixed -> Moving：IC MSE計算専用
    flow_f2m_low = model(
        fixed_bands,
        moving_bands,
    )

    ic_mse = float(
        inverse_consistency_mse(
            flow_m2f_low,
            flow_f2m_low,
        ).item()
    )

    moved_np = moved_tensor[0, 0].cpu().numpy()
    flow_np = flow_m2f_full[0].cpu().numpy()

    fixed_body = make_body_mask(fixed_np)
    moving_body = make_body_mask(moving_np)
    moved_body = make_body_mask(moved_np)

    fixed_lung = make_lung_mask(fixed_np)
    moving_lung = make_lung_mask(moving_np)

    moved_lung = warp_mask_nearest(
        moving_lung,
        flow_m2f_full,
    )

    jacobian = jacobian_determinant(flow_np)

    valid_body = (
        fixed_body
        & valid_reference_mask(
            flow_m2f_full,
            margin=0,
        )
    )

    interior_body = binary_erosion(
        fixed_body,
        iterations=INTERIOR_MARGIN_VOXELS,
    ).astype(bool)

    interior_valid_body = (
        interior_body
        & valid_reference_mask(
            flow_m2f_full,
            margin=INTERIOR_MARGIN_VOXELS,
        )
    )

    z_window = np.zeros_like(
        fixed_body,
        dtype=bool,
    )

    z0 = max(0, Z_START)
    z1 = min(FULL_SIZE[0] - 1, Z_END)

    z_window[z0:z1 + 1] = True

    interior_valid_body_z60_to_z68 = (
        interior_valid_body
        & z_window
    )

    mse_before = np.mean(
        (moving_np - fixed_np) ** 2
    )

    mse_after = np.mean(
        (moved_np - fixed_np) ** 2
    )

    ms_ssim_value, fsim_value = compute_ms_ssim_fsim(
        fixed_np,
        moved_np,
    )

    dice_before, jaccard_before = dice_jaccard(
        fixed_body,
        moving_body,
    )

    dice_after, jaccard_after = dice_jaccard(
        fixed_body,
        moved_body,
    )

    result = {
        "model": MODEL_NAME,
        "pair": pair_dir.name,
        "fixed_file": fixed_path.name,
        "moving_file": moving_path.name,

        "dice_before": dice_before,
        "dice_after": dice_after,

        "jaccard_before": jaccard_before,
        "jaccard_after": jaccard_after,

        "ncc_before": compute_ncc(
            fixed_np,
            moving_np,
        ),
        "ncc_after": compute_ncc(
            fixed_np,
            moved_np,
        ),

        "rmse_hu_before": float(
            np.sqrt(mse_before) * (HU_MAX - HU_MIN)
        ),
        "rmse_hu_after": float(
            np.sqrt(mse_after) * (HU_MAX - HU_MIN)
        ),

        "ssim_after": compute_mean_ssim(
            fixed_np,
            moved_np,
        ),
        "ms_ssim_after": ms_ssim_value,
        "fsim_after": fsim_value,

        "raw_full_folding_percent": float(
            np.mean(jacobian <= 0.0) * 100.0
        ),

        "valid_body_folding_percent": folding_percent(
            jacobian,
            valid_body,
        ),

        "interior_valid_body_folding_percent": folding_percent(
            jacobian,
            interior_valid_body,
        ),

        "interior_valid_body_folding_z60_to_z68_percent": (
            folding_percent(
                jacobian,
                interior_valid_body_z60_to_z68,
            )
        ),

        "jacobian_min": float(jacobian.min()),

        "lung_dice_after": dice_jaccard(
            fixed_lung,
            moved_lung,
        )[0],

        "lung_folding_percent": folding_percent(
            jacobian,
            fixed_lung,
        ),

        "valid_body_fraction_percent": float(
            100.0
            * valid_body.sum()
            / max(fixed_body.sum(), 1)
        ),

        "interior_valid_body_fraction_percent": float(
            100.0
            * interior_valid_body.sum()
            / max(fixed_body.sum(), 1)
        ),

        "flow_magnitude_mean_voxel": float(
            np.sqrt(
                np.sum(flow_np ** 2, axis=0)
            ).mean()
        ),

        # 学習時の inverse_consistency_loss_coarse と同じ定義
        "ic_mse": ic_mse,
    }

    if SAVE_ALL_PAIR_IMAGES:
        result["image_path"] = save_pair_image(
            pair_name=pair_dir.name,
            moving_np=moving_np,
            fixed_np=fixed_np,
            moved_np=moved_np,
            jacobian=jacobian,
            result=result,
        )

    del fixed_tensor
    del moving_tensor
    del moving_bands
    del fixed_bands
    del flow_m2f_low
    del flow_m2f_full
    del flow_f2m_low
    del moved_tensor

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result


# ------------------------------------------------------------
# 9. 全101ペア評価
# ------------------------------------------------------------

pair_dirs = sorted(
    [
        path
        for path in TEST_DATA_ROOT.iterdir()
        if path.is_dir()
        and path.name.lower().startswith("pair")
    ],
    key=natural_sort_key,
)

if not pair_dirs:
    raise FileNotFoundError(
        f"pairフォルダがありません:\n{TEST_DATA_ROOT}"
    )

print(f"\n評価pair数: {len(pair_dirs)}")

rows = []

for index, pair_dir in enumerate(
    tqdm(
        pair_dirs,
        desc="Coarse-only LLL IC fine-tuned evaluation",
    ),
    start=1,
):
    try:
        result = evaluate_pair(pair_dir)
        rows.append(result)

        print(
            f"[{index:03d}/{len(pair_dirs):03d}] "
            f"{pair_dir.name} | "
            f"Dice={result['dice_after']:.5f} | "
            f"NCC={result['ncc_after']:.5f} | "
            f"rawFold={result['raw_full_folding_percent']:.4f}% | "
            f"interiorFold="
            f"{result['interior_valid_body_folding_percent']:.4f}% | "
            f"IC={result['ic_mse']:.6f}"
        )

    except Exception as error:
        print(
            f"[Skip] {pair_dir.name}: {repr(error)}"
        )


# ------------------------------------------------------------
# 10. Pair-wise CSV
# ------------------------------------------------------------

if len(rows) == 0:
    raise RuntimeError("評価成功pairが0件です。")

pairwise_df = pd.DataFrame(rows).sort_values(
    "pair",
    key=lambda column: column.map(natural_sort_key),
).reset_index(drop=True)

pairwise_csv = (
    EVAL_DIR
    / "pairwise_metrics_coarse_only_lll_ic_finetuned.csv"
)

pairwise_df.to_csv(
    pairwise_csv,
    index=False,
    encoding="utf-8-sig",
)

display(pairwise_df.round(6))

print("\nPair-wise CSV:")
print(pairwise_csv)


# ------------------------------------------------------------
# 11. Summary CSV
# ------------------------------------------------------------

raw_worst = pairwise_df.loc[
    pairwise_df[
        "raw_full_folding_percent"
    ].idxmax()
]

valid_worst = pairwise_df.loc[
    pairwise_df[
        "valid_body_folding_percent"
    ].idxmax()
]

interior_worst = pairwise_df.loc[
    pairwise_df[
        "interior_valid_body_folding_percent"
    ].idxmax()
]

z64_worst = pairwise_df.loc[
    pairwise_df[
        "interior_valid_body_folding_z60_to_z68_percent"
    ].idxmax()
]

summary_df = pd.DataFrame(
    [
        {
            "model": MODEL_NAME,
            "n_pairs": int(len(pairwise_df)),

            "dice_before_mean": pairwise_df["dice_before"].mean(),
            "dice_after_mean": pairwise_df["dice_after"].mean(),
            "jaccard_after_mean": pairwise_df[
                "jaccard_after"
            ].mean(),

            "ncc_before_mean": pairwise_df["ncc_before"].mean(),
            "ncc_after_mean": pairwise_df["ncc_after"].mean(),

            "rmse_hu_before_mean": pairwise_df[
                "rmse_hu_before"
            ].mean(),
            "rmse_hu_after_mean": pairwise_df[
                "rmse_hu_after"
            ].mean(),

            "ssim_after_mean": pairwise_df["ssim_after"].mean(),
            "ms_ssim_after_mean": pairwise_df[
                "ms_ssim_after"
            ].mean(),
            "fsim_after_mean": pairwise_df["fsim_after"].mean(),

            "raw_full_folding_mean_percent": pairwise_df[
                "raw_full_folding_percent"
            ].mean(),
            "raw_full_folding_max_percent": pairwise_df[
                "raw_full_folding_percent"
            ].max(),
            "raw_full_worst_pair": raw_worst["pair"],

            "valid_body_folding_mean_percent": pairwise_df[
                "valid_body_folding_percent"
            ].mean(),
            "valid_body_folding_max_percent": pairwise_df[
                "valid_body_folding_percent"
            ].max(),
            "valid_body_worst_pair": valid_worst["pair"],

            "interior_valid_body_folding_mean_percent": pairwise_df[
                "interior_valid_body_folding_percent"
            ].mean(),
            "interior_valid_body_folding_max_percent": pairwise_df[
                "interior_valid_body_folding_percent"
            ].max(),
            "interior_valid_body_worst_pair": interior_worst["pair"],

            "interior_valid_body_folding_z60_to_z68_mean_percent": (
                pairwise_df[
                    "interior_valid_body_folding_z60_to_z68_percent"
                ].mean()
            ),
            "interior_valid_body_folding_z60_to_z68_max_percent": (
                pairwise_df[
                    "interior_valid_body_folding_z60_to_z68_percent"
                ].max()
            ),
            "interior_valid_body_folding_z60_to_z68_worst_pair": (
                z64_worst["pair"]
            ),

            "jacobian_min_mean": pairwise_df[
                "jacobian_min"
            ].mean(),
            "jacobian_global_min": pairwise_df[
                "jacobian_min"
            ].min(),

            "lung_dice_after_mean": pairwise_df[
                "lung_dice_after"
            ].mean(),
            "lung_folding_mean_percent": pairwise_df[
                "lung_folding_percent"
            ].mean(),

            "flow_magnitude_mean_voxel": pairwise_df[
                "flow_magnitude_mean_voxel"
            ].mean(),

            "ic_mse_mean": pairwise_df["ic_mse"].mean(),
            "ic_mse_std": pairwise_df["ic_mse"].std(),
            "ic_mse_max": pairwise_df["ic_mse"].max(),
            "ic_mse_worst_pair": pairwise_df.loc[
                pairwise_df["ic_mse"].idxmax(),
                "pair",
            ],
        }
    ]
)

summary_csv = (
    EVAL_DIR
    / "summary_metrics_coarse_only_lll_ic_finetuned.csv"
)

summary_df.to_csv(
    summary_csv,
    index=False,
    encoding="utf-8-sig",
)

print("\n================ FINAL SUMMARY ================\n")
display(summary_df.round(6))
display(summary_df.T)

print("\nPair-wise CSV:")
print(pairwise_csv)

print("\nSummary CSV:")
print(summary_csv)

if SAVE_ALL_PAIR_IMAGES:
    print("\nSaved images:")
    print(IMAGE_DIR)

print("\nCompleted.")

Device     : cuda:0
TestData   : D:\Saito\Data\TestData
Model path : D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\model_coarse_only_lll_ic_finetuned_30k_final.pth
Output dir : D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_coarse_only_lll_ic_finetuned_30k
Direction  : Moving -> Fixed
[64, 128, 128]

Model loading completed.
Checkpoint epoch: 30000
Architecture    : unknown
Loss            : unknown

評価pair数: 101

Coarse-only LLL IC fine-tuned evaluation:   0%|          | 0/101 [00:00<?, ?it/s]

[001/101] pair1 | Dice=0.99386 | NCC=0.99263 | rawFold=1.8430% | interiorFold=1.8255% | IC=0.252458
[002/101] pair2 | Dice=0.99327 | NCC=0.99259 | rawFold=1.0931% | interiorFold=1.7712% | IC=0.231494
[003/101] pair3 | Dice=0.99382 | NCC=0.99203 | rawFold=1.3930% | interiorFold=2.2932% | IC=0.214796
[004/101] pair4 | Dice=0.99378 | NCC=0.99185 | rawFold=1.0766% | interiorFold=2.5216% | IC=0.196643
[005/101] pair5 | Dice=0.99408 | NCC=0.99115 | rawFold=1.1817% | interiorFold=2.7925% | IC=0.204965
[006/101] pair6 | Dice=0.99464 | NCC=0.99356 | rawFold=0.7456% | interiorFold=1.5710% | IC=0.222554
[007/101] pair7 | Dice=0.99466 | NCC=0.99232 | rawFold=1.7324% | interiorFold=2.0568% | IC=0.233474
[008/101] pair8 | Dice=0.99455 | NCC=0.99155 | rawFold=2.2483% | interiorFold=2.5043% | IC=0.263572
[009/101] pair9 | Dice=0.99350 | NCC=0.99256 | rawFold=0.7309% | interiorFold=1.5270% | IC=0.156748
[010/101] pair10 | Dice=0.99302 | NCC=0.99300 | rawFold=0.7920% | interiorFold=1.5323% | IC=0.160426
[011/101] pair11 | Dice=0.99396 | NCC=0.99160 | rawFold=1.7217% | interiorFold=2.2925% | IC=0.232013
[012/101] pair12 | Dice=0.99270 | NCC=0.99054 | rawFold=2.8469% | interiorFold=6.4391% | IC=0.536689
[013/101] pair13 | Dice=0.99314 | NCC=0.99389 | rawFold=0.5789% | interiorFold=1.5860% | IC=0.134598
[014/101] pair14 | Dice=0.99366 | NCC=0.99412 | rawFold=0.7197% | interiorFold=1.8468% | IC=0.158050
[015/101] pair15 | Dice=0.99464 | NCC=0.99283 | rawFold=0.8708% | interiorFold=1.4968% | IC=0.208172
[016/101] pair16 | Dice=0.99509 | NCC=0.99273 | rawFold=0.9583% | interiorFold=2.0418% | IC=0.212514
[017/101] pair17 | Dice=0.99548 | NCC=0.98993 | rawFold=2.3421% | interiorFold=2.5496% | IC=0.315902
[018/101] pair18 | Dice=0.99406 | NCC=0.98478 | rawFold=4.1316% | interiorFold=5.6981% | IC=0.563840
[019/101] pair19 | Dice=0.99512 | NCC=0.99224 | rawFold=0.8717% | interiorFold=1.6652% | IC=0.235372
[020/101] pair20 | Dice=0.99454 | NCC=0.98835 | rawFold=1.4595% | interiorFold=2.3240% | IC=0.270918
[021/101] pair21 | Dice=0.99504 | NCC=0.99318 | rawFold=0.8814% | interiorFold=1.7076% | IC=0.278059
[022/101] pair22 | Dice=0.99499 | NCC=0.98912 | rawFold=1.8346% | interiorFold=3.6398% | IC=0.263637
[023/101] pair23 | Dice=0.99339 | NCC=0.99162 | rawFold=0.8292% | interiorFold=1.8583% | IC=0.182253
[024/101] pair24 | Dice=0.99346 | NCC=0.99407 | rawFold=0.4984% | interiorFold=1.2106% | IC=0.138978
[025/101] pair25 | Dice=0.99358 | NCC=0.99313 | rawFold=0.8408% | interiorFold=1.6101% | IC=0.191974
[026/101] pair26 | Dice=0.99228 | NCC=0.98994 | rawFold=1.2905% | interiorFold=3.0132% | IC=0.210071
[027/101] pair27 | Dice=0.99352 | NCC=0.99029 | rawFold=1.2606% | interiorFold=3.0544% | IC=0.203778
[028/101] pair28 | Dice=0.99359 | NCC=0.99299 | rawFold=0.8306% | interiorFold=1.9723% | IC=0.172655
[029/101] pair29 | Dice=0.99320 | NCC=0.99084 | rawFold=1.2675% | interiorFold=3.2378% | IC=0.219160
[030/101] pair30 | Dice=0.99310 | NCC=0.99208 | rawFold=0.9752% | interiorFold=2.2427% | IC=0.181076
[031/101] pair31 | Dice=0.99299 | NCC=0.98909 | rawFold=2.1321% | interiorFold=3.3508% | IC=0.213679
[032/101] pair32 | Dice=0.99293 | NCC=0.99009 | rawFold=3.3035% | interiorFold=5.8172% | IC=0.710845
[033/101] pair33 | Dice=0.99369 | NCC=0.99170 | rawFold=2.2988% | interiorFold=2.0085% | IC=0.313918
[034/101] pair34 | Dice=0.99049 | NCC=0.98105 | rawFold=5.0645% | interiorFold=8.6808% | IC=0.850354
[035/101] pair35 | Dice=0.99384 | NCC=0.99318 | rawFold=0.8215% | interiorFold=1.4651% | IC=0.238043
[036/101] pair36 | Dice=0.99384 | NCC=0.98801 | rawFold=1.8637% | interiorFold=3.2611% | IC=0.299364
[037/101] pair37 | Dice=0.99338 | NCC=0.98678 | rawFold=3.5041% | interiorFold=4.4526% | IC=0.415712
[038/101] pair38 | Dice=0.99119 | NCC=0.98883 | rawFold=0.9733% | interiorFold=2.0611% | IC=0.202108
[039/101] pair39 | Dice=0.99124 | NCC=0.98788 | rawFold=1.1317% | interiorFold=2.8933% | IC=0.209828
[040/101] pair40 | Dice=0.98999 | NCC=0.98922 | rawFold=1.8585% | interiorFold=3.6604% | IC=0.271094
[041/101] pair41 | Dice=0.99439 | NCC=0.99474 | rawFold=0.5902% | interiorFold=1.4563% | IC=0.152296
[042/101] pair42 | Dice=0.99514 | NCC=0.99287 | rawFold=0.6760% | interiorFold=1.4576% | IC=0.186771
[043/101] pair43 | Dice=0.99499 | NCC=0.99100 | rawFold=2.1041% | interiorFold=2.8113% | IC=0.222871
[044/101] pair44 | Dice=0.99468 | NCC=0.98920 | rawFold=3.6543% | interiorFold=3.4093% | IC=0.298776
[045/101] pair45 | Dice=0.99486 | NCC=0.99434 | rawFold=0.6487% | interiorFold=1.3836% | IC=0.191276
[046/101] pair46 | Dice=0.96854 | NCC=0.95528 | rawFold=2.6061% | interiorFold=6.9134% | IC=0.914988
[047/101] pair47 | Dice=0.99236 | NCC=0.99071 | rawFold=2.6064% | interiorFold=3.0670% | IC=0.286436
[048/101] pair48 | Dice=0.99213 | NCC=0.98903 | rawFold=3.3103% | interiorFold=4.6114% | IC=0.330201
[049/101] pair49 | Dice=0.98995 | NCC=0.98796 | rawFold=3.7936% | interiorFold=6.9037% | IC=0.586028
[050/101] pair50 | Dice=0.99028 | NCC=0.98761 | rawFold=3.2000% | interiorFold=4.9396% | IC=0.413630
[051/101] pair51 | Dice=0.99199 | NCC=0.98576 | rawFold=4.9640% | interiorFold=7.1633% | IC=0.537881
[052/101] pair52 | Dice=0.99401 | NCC=0.99170 | rawFold=1.1193% | interiorFold=2.0531% | IC=0.201148
[053/101] pair53 | Dice=0.99228 | NCC=0.99062 | rawFold=2.2759% | interiorFold=2.4996% | IC=0.262610
[054/101] pair54 | Dice=0.99159 | NCC=0.98666 | rawFold=2.5856% | interiorFold=4.3153% | IC=0.330779
[055/101] pair55 | Dice=0.99388 | NCC=0.99000 | rawFold=2.7336% | interiorFold=2.6738% | IC=0.266294
[056/101] pair56 | Dice=0.99240 | NCC=0.99234 | rawFold=1.6161% | interiorFold=2.0925% | IC=0.227543
[057/101] pair57 | Dice=0.99130 | NCC=0.98766 | rawFold=2.4325% | interiorFold=4.3779% | IC=0.340077
[058/101] pair58 | Dice=0.99374 | NCC=0.99006 | rawFold=1.6206% | interiorFold=2.5270% | IC=0.251574
[059/101] pair59 | Dice=0.99158 | NCC=0.98844 | rawFold=2.0534% | interiorFold=3.5647% | IC=0.304231
[060/101] pair60 | Dice=0.99397 | NCC=0.99160 | rawFold=1.1560% | interiorFold=2.1608% | IC=0.230842
[061/101] pair61 | Dice=0.99139 | NCC=0.98434 | rawFold=4.5941% | interiorFold=7.9984% | IC=0.849642
[062/101] pair62 | Dice=0.99266 | NCC=0.98882 | rawFold=2.9962% | interiorFold=5.7123% | IC=0.506488
[063/101] pair63 | Dice=0.99278 | NCC=0.99282 | rawFold=0.6262% | interiorFold=1.1645% | IC=0.165559
[064/101] pair64 | Dice=0.99326 | NCC=0.99356 | rawFold=0.6276% | interiorFold=1.2366% | IC=0.162230
[065/101] pair65 | Dice=0.99324 | NCC=0.99404 | rawFold=0.7235% | interiorFold=1.7929% | IC=0.152640
[066/101] pair66 | Dice=0.98975 | NCC=0.98535 | rawFold=2.9138% | interiorFold=6.8197% | IC=0.800077
[067/101] pair67 | Dice=0.99495 | NCC=0.99192 | rawFold=2.0193% | interiorFold=2.3899% | IC=0.275773
[068/101] pair68 | Dice=0.99418 | NCC=0.99150 | rawFold=1.4163% | interiorFold=2.9506% | IC=0.188778
[069/101] pair69 | Dice=0.99113 | NCC=0.99047 | rawFold=1.1073% | interiorFold=1.8338% | IC=0.219994
[070/101] pair70 | Dice=0.99170 | NCC=0.99282 | rawFold=0.6061% | interiorFold=1.1742% | IC=0.167080
[071/101] pair71 | Dice=0.99277 | NCC=0.99405 | rawFold=0.5008% | interiorFold=0.9813% | IC=0.174337
[072/101] pair72 | Dice=0.95470 | NCC=0.91771 | rawFold=4.7805% | interiorFold=8.1187% | IC=1.599889
[073/101] pair73 | Dice=0.99318 | NCC=0.98687 | rawFold=4.0617% | interiorFold=7.1470% | IC=0.766502
[074/101] pair74 | Dice=0.99468 | NCC=0.99200 | rawFold=1.7769% | interiorFold=2.9401% | IC=0.298805
[075/101] pair75 | Dice=0.99416 | NCC=0.99229 | rawFold=1.5958% | interiorFold=1.9970% | IC=0.208645
[076/101] pair76 | Dice=0.99372 | NCC=0.99203 | rawFold=1.5418% | interiorFold=2.5616% | IC=0.164517
[077/101] pair77 | Dice=0.90643 | NCC=0.85318 | rawFold=6.3381% | interiorFold=11.4689% | IC=4.298853
[078/101] pair78 | Dice=0.89492 | NCC=0.83627 | rawFold=7.0472% | interiorFold=13.8917% | IC=6.262880
[079/101] pair79 | Dice=0.90925 | NCC=0.86162 | rawFold=6.0426% | interiorFold=10.7422% | IC=4.582095
[080/101] pair80 | Dice=0.89901 | NCC=0.83865 | rawFold=6.6079% | interiorFold=11.0410% | IC=5.507294
[081/101] pair81 | Dice=0.99178 | NCC=0.98888 | rawFold=2.1405% | interiorFold=2.5224% | IC=0.322203
[082/101] pair82 | Dice=0.98824 | NCC=0.98317 | rawFold=1.6593% | interiorFold=2.6812% | IC=0.311374
[083/101] pair83 | Dice=0.99117 | NCC=0.98374 | rawFold=2.1532% | interiorFold=2.9581% | IC=0.414681
[084/101] pair84 | Dice=0.99073 | NCC=0.98310 | rawFold=2.1957% | interiorFold=4.4822% | IC=0.347189
[085/101] pair85 | Dice=0.99399 | NCC=0.98456 | rawFold=2.2208% | interiorFold=4.1872% | IC=0.352560
[086/101] pair86 | Dice=0.99148 | NCC=0.98892 | rawFold=1.5639% | interiorFold=2.7460% | IC=0.327830
[087/101] pair87 | Dice=0.99340 | NCC=0.99253 | rawFold=0.8843% | interiorFold=1.6516% | IC=0.247849
[088/101] pair88 | Dice=0.99361 | NCC=0.99308 | rawFold=1.1439% | interiorFold=1.9365% | IC=0.229306
[089/101] pair89 | Dice=0.97832 | NCC=0.96337 | rawFold=5.3137% | interiorFold=9.9275% | IC=1.418101
[090/101] pair90 | Dice=0.96876 | NCC=0.94495 | rawFold=5.9930% | interiorFold=10.7317% | IC=1.474672
[091/101] pair91 | Dice=0.99396 | NCC=0.99096 | rawFold=1.2579% | interiorFold=2.4118% | IC=0.205125
[092/101] pair92 | Dice=0.99272 | NCC=0.98922 | rawFold=1.4429% | interiorFold=2.6134% | IC=0.222700
[093/101] pair93 | Dice=0.99404 | NCC=0.99378 | rawFold=0.5835% | interiorFold=1.3593% | IC=0.167153
[094/101] pair94 | Dice=0.99294 | NCC=0.99143 | rawFold=1.9292% | interiorFold=2.3737% | IC=0.254919
[095/101] pair95 | Dice=0.99266 | NCC=0.99204 | rawFold=1.9285% | interiorFold=2.4587% | IC=0.228714
[096/101] pair96 | Dice=0.99386 | NCC=0.99312 | rawFold=1.1378% | interiorFold=1.8765% | IC=0.245821
[097/101] pair97 | Dice=0.99433 | NCC=0.99322 | rawFold=0.7677% | interiorFold=1.4624% | IC=0.203181
[098/101] pair98 | Dice=0.99457 | NCC=0.99339 | rawFold=0.9527% | interiorFold=1.9242% | IC=0.185976
[099/101] pair99 | Dice=0.99474 | NCC=0.99234 | rawFold=0.9280% | interiorFold=1.5980% | IC=0.251470
[100/101] pair100 | Dice=0.99363 | NCC=0.99279 | rawFold=0.6114% | interiorFold=1.1670% | IC=0.163371
[101/101] pair101 | Dice=0.99352 | NCC=0.99356 | rawFold=1.0622% | interiorFold=1.7657% | IC=0.219288

,model,pair,fixed_file,moving_file,dice_before,dice_after,jaccard_before,jaccard_after,ncc_before,ncc_after,...,interior_valid_body_folding_percent,interior_valid_body_folding_z60_to_z68_percent,jacobian_min,lung_dice_after,lung_folding_percent,valid_body_fraction_percent,interior_valid_body_fraction_percent,flow_magnitude_mean_voxel,ic_mse,image_path
0,30k_coarse_only_lll_ic_finetuned,pair1,fixed_masked_B_MIC00197_2019_0406.npz,registered_masked_A_MIC00197_2018_0428.npz,0.961797,0.993859,0.926405,0.987793,0.928469,0.992631,...,1.825451,1.007682,-8.032995,0.904579,1.573820,99.944213,83.291195,1.391269,0.252458,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
1,30k_coarse_only_lll_ic_finetuned,pair2,fixed_masked_B_MIC00761_2020_0926.npz,registered_masked_A_MIC00761_2019_0727.npz,0.981110,0.993269,0.962920,0.986628,0.962952,0.992588,...,1.771180,1.573112,-9.117491,0.909043,1.884039,99.891662,81.989555,1.304247,0.231494,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
2,30k_coarse_only_lll_ic_finetuned,pair3,fixed_masked_B_MIC03568_2019_0824.npz,registered_masked_A_MIC03568_2018_0825.npz,0.963118,0.993822,0.928860,0.987720,0.928717,0.992027,...,2.293226,2.473479,-7.080524,0.843842,2.316654,99.946054,82.930456,1.442814,0.214796,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
3,30k_coarse_only_lll_ic_finetuned,pair4,fixed_masked_B_MIC03568_2020_0829.npz,registered_masked_A_MIC03568_2018_0825.npz,0.982659,0.993777,0.965908,0.987631,0.957978,0.991850,...,2.521586,1.454833,-4.999599,0.855031,3.972035,99.916393,81.827218,1.338172,0.196643,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
4,30k_coarse_only_lll_ic_finetuned,pair5,fixed_masked_B_MIC03568_2020_0829.npz,registered_masked_A_MIC03568_2019_0824.npz,0.986525,0.994083,0.973408,0.988236,0.959973,0.991150,...,2.792461,2.104667,-4.795894,0.841360,4.647542,99.918090,81.614067,1.441799,0.204965,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,30k_coarse_only_lll_ic_finetuned,pair97,fixed_masked_B_MIC45438_2020_0824.npz,registered_masked_A_MIC45438_2019_0903.npz,0.979977,0.994330,0.960741,0.988723,0.947270,0.993219,...,1.462433,1.475213,-2.720105,0.771784,1.988350,99.911700,82.546278,1.884112,0.203181,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
97,30k_coarse_only_lll_ic_finetuned,pair98,fixed_masked_B_MIC52743_2020_0125.npz,registered_masked_A_MIC52743_2018_1213.npz,0.978022,0.994569,0.956990,0.989197,0.952752,0.993387,...,1.924198,2.139693,-5.164343,0.876141,2.228216,99.913081,82.605379,1.640482,0.185976,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
98,30k_coarse_only_lll_ic_finetuned,pair99,fixed_masked_B_MIC53652_2020_1219.npz,registered_masked_A_MIC53652_2019_1213.npz,0.981859,0.994742,0.964364,0.989540,0.947066,0.992336,...,1.598048,0.983446,-5.274282,0.849029,1.980716,99.955748,83.444353,1.711398,0.251470,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
99,30k_coarse_only_lll_ic_finetuned,pair100,fixed_masked_B_MIC53770_2019_1111.npz,registered_masked_A_MIC53770_2018_1128.npz,0.980435,0.993628,0.961621,0.987336,0.954214,0.992794,...,1.167034,0.524086,-4.290873,0.939365,0.875135,99.888047,83.098710,1.271413,0.163371,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...
100,30k_coarse_only_lll_ic_finetuned,pair101,fixed_masked_B_MIC53945_2020_0515.npz,registered_masked_A_MIC53945_2019_0604.npz,0.980744,0.993517,0.962215,0.987118,0.961095,0.993560,...,1.765694,1.257416,-3.269469,0.903644,2.194478,99.839409,82.812683,1.286062,0.219288,D:\Saito\fullres_trilinear_ic_beta1e3_80k\coar...

Pair-wise CSV:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_coarse_only_lll_ic_finetuned_30k\pairwise_metrics_coarse_only_lll_ic_finetuned.csv

================ FINAL SUMMARY ================

,model,n_pairs,dice_before_mean,dice_after_mean,jaccard_after_mean,ncc_before_mean,ncc_after_mean,rmse_hu_before_mean,rmse_hu_after_mean,ssim_after_mean,...,interior_valid_body_folding_z60_to_z68_worst_pair,jacobian_min_mean,jacobian_global_min,lung_dice_after_mean,lung_folding_mean_percent,flow_magnitude_mean_voxel,ic_mse_mean,ic_mse_std,ic_mse_max,ic_mse_worst_pair
0,30k_coarse_only_lll_ic_finetuned,101,0.959418,0.988571,0.978007,0.920009,0.983142,411.771446,171.831054,0.892246,...,pair84,-7.851125,-21.13275,0.79859,2.741671,1.764373,0.519343,0.995228,6.26288,pair78

                                                                                   0
model                                               30k_coarse_only_lll_ic_finetuned
n_pairs                                                                          101
dice_before_mean                                                            0.959418
dice_after_mean                                                             0.988571
jaccard_after_mean                                                          0.978007
ncc_before_mean                                                             0.920009
ncc_after_mean                                                              0.983142
rmse_hu_before_mean                                                       411.771446
rmse_hu_after_mean                                                        171.831054
ssim_after_mean                                                             0.892246
ms_ssim_after_mean                                                          0.943173
fsim_after_mean                                                              0.93399
raw_full_folding_mean_percent                                               2.023157
raw_full_folding_max_percent                                                7.047176
raw_full_worst_pair                                                           pair78
valid_body_folding_mean_percent                                             4.085954
valid_body_folding_max_percent                                             14.251504
valid_body_worst_pair                                                         pair78
interior_valid_body_folding_mean_percent                                    3.452595
interior_valid_body_folding_max_percent                                    13.891676
interior_valid_body_worst_pair                                                pair78
interior_valid_body_folding_z60_to_z68_mean_per...                          1.776337
interior_valid_body_folding_z60_to_z68_max_percent                          7.155362
interior_valid_body_folding_z60_to_z68_worst_pair                             pair84
jacobian_min_mean                                                          -7.851125
jacobian_global_min                                                        -21.13275
lung_dice_after_mean                                                         0.79859
lung_folding_mean_percent                                                   2.741671
flow_magnitude_mean_voxel                                                   1.764373
ic_mse_mean                                                                 0.519343
ic_mse_std                                                                  0.995228
ic_mse_max                                                                   6.26288
ic_mse_worst_pair                                                             pair78

Pair-wise CSV:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_coarse_only_lll_ic_finetuned_30k\pairwise_metrics_coarse_only_lll_ic_finetuned.csv

Summary CSV:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_coarse_only_lll_ic_finetuned_30k\summary_metrics_coarse_only_lll_ic_finetuned.csv

Saved images:
D:\Saito\fullres_trilinear_ic_beta1e3_80k\coarse_only_lll_ic_finetune_30k\testdata_evaluation_coarse_only_lll_ic_finetuned_30k\pair_images

Completed.